### ISSUE TITLE
Empty excel file when running on custom area (eg. liberia landscape)

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#100]

**Comment by azvoleff** [comment]
Can you test this on the latest version (0.48, avail through QGIS)? I don't see this anymore.

**Comment by mgroglich** [comment]
What do you mean by "you don't see this anymore"? The excel file still is empty for me.

**Comment by azvoleff** [comment]
This is I think due to the problem with that coordinate system (see the other issue). I'll add more checks that the AOI transforms correctly to WGS84, but the way to fix this is to supply an AOI in a CRS that QGIS recognizes.
