### ISSUE TITLE
Pop up window to define coordinate system when using custom area shapefile

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#101]

**Comment by azvoleff** [comment]
Can you test this on the latest version (0.48, avail through QGIS)? I don't see this, so might have been fixed. Albeit inadvertently...

**Comment by azvoleff** [comment]
Ok, I tested on this file, and I see this with that shapefile, but it is because the coordinate system (WGS_1984_Complex_UTM_Zone_29N) is not known to QGIS. You can test this by dragging the shapefile into QGIS directly without using our tool.
