### ISSUE TITLE
Add IPCC climate zones to gee_datasets.json

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#105]
Can you add the IPCC climate zones asset to the gee_datasets.json file under LDMP/data/gee_datasets.json? I need it to be accessible through the plugin download script so that I can make it automatically pull it down when someone wants to run SOC locally with custom LC data. It will need to either be in a new category (say Climate zones?) or you could rename the category the agroecological zones are listed under now to something that would cover both of them.

**Comment by mgroglich** [comment]
I just added it. If it is fine, please close the task, if not... I'll be back!
