### ISSUE TITLE
Error when trying to compute SDG for Kenya using CI's landscape

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#107]
Hi Alex,

Still not being able to compute SDG for the landscapes. I checked and the coordinate system is correct, but when trying to run the integrate tool we get the following errors: :"Error masking SDG 15.3.1"
The file we are trying to use is in the link below:
https://www.dropbox.com/s/84xj1b0b7bay2z3/UTM_Projection.zip?dl=0

**Comment by azvoleff** [comment]
Can you add the output you get from the trends.earth messages panel? And what version are you using?

**Comment by mgroglich** [comment]
Please ignore... I looked with more detail the shapefile Gabe was trying to use, and that was the problem. It was a mess with gaps everywhere and overlapping sections. TRENDS.EARTH is bullet proof!
