### ISSUE TITLE
SOC load data error

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#132]
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'XSize' 
Traceback (most recent call last):
  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\data_io.py", line 377, in ok_clicked
    resp = add_layer(f, self.layer_list[row][2], self.layer_list[row][3])
  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\layers.py", line 314, in add_layer
    cutoff = get_cutoff(f, band_number, band_info, [100 - style['ramp']['percent stretch']])
  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\layers.py", line 198, in get_cutoff
    d = get_sample(f, band_number)
  File "D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP\layers.py", line 170, in get_sample
    xsize = b.XSize
AttributeError: 'NoneType' object has no attribute 'XSize'

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.15 Las Palmas, ac2d111ed1 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
D:\Documents and Settings\mgonzalez-roglich\.qgis2\python\plugins\LDMP\ext-libs
D:/Documents and Settings/mgonzalez-roglich/.qgis2/python
D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
D:/Documents and Settings/mgonzalez-roglich/.qgis2//python
D:/Documents and Settings/mgonzalez-roglich/.qgis2/python/plugins\LDMP

**Comment by azvoleff** [comment]
Fixed.
