### ISSUE TITLE
Custom land cover no data

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#145]
If when loading a custom land cover dataset using the import tool one record is empty for the attribute being selected has no data, it is identified as NULL by the tool and then in fails. Would it be possible to recognize them as NOData?

You can use this to test:

https://www.dropbox.com/s/ph1b3ggltgwy3sx/colombia_2012_null.zip?dl=0

**Comment by azvoleff** [comment]
That file works fine for me. Maybe was related to the other fix I made? Let me know if you are still having issues with NULL one you have 0.56 installed, and send me the error message.

**Comment by azvoleff** [comment]
This should be fixed by f4518e3. Can you confirm this is working if you use paver to install the latest github version?
