### ISSUE TITLE
Discuss resolution of the final SDG when using local data

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#148]
We currently use the finer resolution when integrating SOC with local land cover for the output, but when integrating the final SDG everything is resampled back to 250m. Some countries asked then, what is the point of using higher spatial resolution land cover if the final output is 250m? They do have a point. I don't have an answer, but lets discuss. Maybe using the finer of the inputs would make sense here as well.

**Comment by azvoleff** [comment]
Add resolution to output file

**Comment by azvoleff** [comment]
Also ensure that all outputs are resampled to the _highest_ resolution among the input data layers, not the lowest. @mgroglich - that is what we agreed, right?

**Comment by mgroglich** [comment]
Yeap!
