### ISSUE TITLE
Countries crossing the 180 meridian

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#149]
I am sure you've thought about this, but is there a way to make the file downloaded be 2 separate tiles (like the tool does for very big countries), one on the far east and another tile in the far west? For example, I downloaded the results for Kiribati, and the data covers the whole world from -180 to +180, making the size of the file quite bit and the processing time for the SDG quite long. Pyramids for example take 50 Gb.

**Comment by mgroglich** [comment]
I should have looked at the data before. It is tiled, I guess the question is, can we skip empty tiles?

**Comment by azvoleff** [comment]
Need to make sure that SDG layer calculates for countries that are split across the 180th

**Comment by azvoleff** [comment]
Fixed in 85bc2d782302bbdc5e2ca0c8435e172655ea2123.
