### ISSUE TITLE
Trends.Earth productivity failing for very small areas, or maybe no data areas

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#153]
I am running the Trends.Earth productivity layers (traj, perf, and state) for all countries. Several are failing - so far Antarctica and Ashmore and Cartier Islands. The error I am getting from GEE (not sure where from) is: "Image.remap: List of values to remap must not be empty." Do you have any idea why this might happen? Assume it is due to trying to remap a class that doesn't actually exist in the data.

**Comment by mgroglich** [comment]
It is also failing for Cook Islands. But I now have a question for you @azvoleff . When using the shapefile it failed, however, if I created a bounding box shapefile in Qgis and used that for calculation, the tool run correctly. My understanding was that the way the tool was set up, a bounding box was used when submitting the task, but that seems not to be the case. Any ideas?

**Comment by azvoleff** [comment]
Another thing to check is how the geojsons the tool is computing for each bounding task compare. Look either in the details tab for each task in QGIS, or under executions -> expand the info for the particular task -> "Execution params". The geojsons listed there are what the plugin is computing for the bounding box - there is usually just one polygon, but if the AOI crosses the 180th meridian there will be two sets of coordinates in the geojson. Can you copy and paste the geojsons from each task here?
