### ISSUE TITLE
Symbology of the trajectory layer

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#160]
I think for trajectory we should by default only show the "degradation" layer, and leave the slope in the stuck, but not load it at once. Most people won't really use it and it is a but confusing having both, and it is also different from what we do for State and Performance.

Also, I'd simply show 3 classes: improvement, stable, and decreasing instead of the different significance levels we currently have. Again, this is kind of irrelevant for most people, and different from how we present the other layers.

**Comment by azvoleff** [comment]
Agreed. Fixed in latest version of landdegradation package.
