### ISSUE TITLE
Custom land cover extent

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#166]
Several users are having the same problem. They use a custom land cover map which has a smaller extent than the final boundary map they want to use for calculations. The input land cover map menu does not require the boundary layer, so there is no way to fix that in our tool (I've been doing it out side). How hard would it be to add the area menu option to the import custom land cover menu (and maybe also to SOC and LPD), and then fill everything outside of the land cover but inside of the area shapefile as NoData? That would solve the problem Uruguay and Costa Rica where having, and that I imagine many having also.

**Comment by azvoleff** [comment]
Not sure I understand this - they want to use a land cover map that doesn't cover the entire area? Why? In that case why don't they reduce the area covered by the boundary so it matches the land cover map? Using a larger boundary layer won't have any benefit since the no data will carry through to the final indicator.

**Comment by mgroglich** [comment]
Yes, you understand it correctly. The mismatch is on most cases small (e.g. missing a small island). The benefit would be that the excel file would report the total area correctly, and if the LC dataset does not cover, let's say the small island, then that would be tabulated as no data.

**Comment by azvoleff** [comment]
That makes sense. Will keep it on the list, but not for the near future :)

**Comment by azvoleff** [comment]
Closing as #328 would address this.
