### ISSUE TITLE
Adding Hansen and carbon data to gee_datasets.json

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#169]
@mgroglich - can you add the Hansen data and all the carbon data used in the carbon tool to LDMP/data/gee_datasets.json? I added enough on the Hansen data to make the plugin run, but would be good to have full metadata, correct bounds, etc.

**Comment by azvoleff** [comment]
@gdaldegan - not a priority, but can you add the metadata on that dataset to the gee_datasets json file?

**Comment by gdaldegan** [comment]
@azvoleff not sure what specific datasets
