### ISSUE TITLE
36% of No data in kenya forest analysis

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#174]
Hi Alex,

Do you know where so much no data is coming from? The forest map seems to be covering the whole country and the water bodies are not so extensive. Results below if you don't want to run them

https://www.dropbox.com/s/b6hkpc4mofusmbk/Forest_kenya.zip?dl=0

**Comment by mgroglich** [comment]
So the no data is coming from the biomass raster, but I think we should not use that to define no data, because there is no biomass data in areas with no forest, and the way it is presented in the table right no makes it seem like there is no data for forest cover.

**Comment by azvoleff** [comment]
Ok. That means I need to fix in my end, right? Just change how I summarize?

**Comment by azvoleff** [comment]
@mgroglich - is this still an issue (above links is dead)? If so, any thoughts on how to fix? Does this need a fix in the GEE code? Or in my Python summary code?

**Comment by azvoleff** [comment]
@mgroglich - this still an issue?

**Comment by mgroglich** [comment]
No longer and issue.
