### ISSUE TITLE
Urban - Link in settings tab only allows to copy URL link

### ISSUE THREAD

**Issue by MLNoon** [ConservationInternational/trends.earth#185]
Is there any way to follow a link by clicking on it? Clicking prompts me to copy link location by right clicking on the the "Urban Mapper page", but that may not be clear for users.

![mapper_link](https://user-images.githubusercontent.com/19840094/49170968-63d6a000-f30b-11e8-9e9c-9dc9fa906f0d.PNG)

**Comment by azvoleff** [comment]
Done.
