### ISSUE TITLE
SDG 11.3.1 - Area calculations/clipping

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#188]
The area calculations are correct. However, it took me a while to figure out why the areas did not add up to the area of the square I was seeing in the map (20km by 20 km). I know... circles! Would it be possible to clip the layers in the last step, like we do for sgd 15.3.1. This will make it clear for the user to understand what area the excel is representing. In particular when using their own file with a complex shape.

**Comment by azvoleff** [comment]
Done!
