### ISSUE TITLE
Modify text in C tool for biomass dataset

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#194]
For the biomass dataset options, we currently say that the 30m data is only for the tropics. Some people asked me what are the limits of the tropics. Can we please add that the limits are "30 latitude north and south"?

**Comment by azvoleff** [comment]
Done. Only I labeled it "Default Woods Hole Research Center (30 m resolution, 30N - 30S only)" just so the text would fit.
