### ISSUE TITLE
Tool failing with complex shapefiles

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#197]
This is an example of one of the files which was failing on the plugin (for all the modules)

https://www.dropbox.com/s/033oepkxh5ozc3g/polygon_uniq.zip?dl=0

Any idea what the issue would be?

**Comment by azvoleff** [comment]
@gdaldegan - can you look into this and see if the above shapefile above  still throws an error? If not, just close this one.

**Comment by azvoleff** [comment]
@gdaldegan - is this still an issue?

**Comment by gdaldegan** [comment]
@azvoleff tried to run all modules with the shapefile Mariano shared above and unfortunately it is still throwing an error

**Comment by azvoleff** [comment]
Closing this as there are invalid geometries in that shapefile, which is why it is failing. Commit 
eb52c1f adds a better message notifying users if there are invalid geometries, and how to check their files.
