### ISSUE TITLE
Replace agb to 30 global dataset

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#200]
Replace current data to the following asset:
var agb = ee.ImageCollection("users/geflanddegradation/toolbox_datasets/forest_agb_30m_gfw").mosaic().unmask(0);

Source:
http://data.globalforestwatch.org/datasets/8f93a6f94a414f9588ce4657a39c59ff_1

It would also require to edit the label in QGIS to indicate that it is global (not only tropical as the current one).

**Comment by azvoleff** [comment]
Done!
