### ISSUE TITLE
SDG 11 code: Update kernel radius to match UN-Habitat guidelines

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#208]
Update radius in line below to 564  to attain a sum area of 1km2 per walking distance circle)

var dens = built_up.reduceNeighborhood({reducer: ee.Reducer.mean(),kernel: ee.Kernel.circle(`564,"meters")});

**Comment by azvoleff** [comment]
@mgroglich Can you check that this is done? And close this if we're good.

**Comment by azvoleff** [comment]
Fixed in #235.
