### ISSUE TITLE
UrbanSummary.xlsx has conflicting units for 'land class by year' and 'City area change'

### ISSUE THREAD

**Issue by bmcandr** [ConservationInternational/trends.earth#210]
Correct mismatch of units in UrbanSummary.xlsx template (LDMP/data/UrbanSummaryTable.xlsx). Cell D5 should list `City area change (sq km)` as `City area change (hectares)` to align with cell formulas that sum values for `Area (in hectares) of each land class by year`.

**Comment by gdaldegan** [comment]
Implemented the required change to ensure consistency
