### ISSUE TITLE
Error message when canceled TE processing

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#212]
QGIS displayed a python error message when I canceled a long lasting processing this morning. See attached:
<img width="586" alt="pythonError_whenCanceledProcessing" src="https://user-images.githubusercontent.com/22821787/66763445-d2661300-ee75-11e9-9183-51b58be7144c.PNG">

**Comment by azvoleff** [comment]
Duplicate of #19.
