### ISSUE TITLE
Update install instructions to take account of QGIS3 install from zipfile option

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#218]

**Comment by azvoleff** [comment]
@gdaldegan . Can you update the readme.md file to mention that now you can install the zipfile directly from within QGIS? No need to extract the files to the folder manually anymore.

Also see #231, which is related (more readme updates)

**Comment by gdaldegan** [comment]
Hi Alex,

Sure thing! Will do this and other updates on the readme file tomorrow, as
I’m presenting all day long today.

Best!
Gabriel

**Comment by gdaldegan** [comment]
@azvoleff have you received the pull request I submitted on this issue?

**Comment by gdaldegan** [comment]
included instructions on how to install TE for QGIS3 and greater from a zipfile
