### ISSUE TITLE
Update climate datasets

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#222]
Update ET, precipitation and soil moisture datasets to most current year available.

**Comment by azvoleff** [comment]
@gdaldegan - I believe this is already done, correct? If so can you close?

**Comment by gdaldegan** [comment]
@mgroglich have you had the chance to update these datasets? I recall we updated CHIRPS and MOD16A2 (ET), but not sure about ERA I and MERRA 2

**Comment by azvoleff** [comment]
@mgroglich - any updates here?

**Comment by mgroglich** [comment]
I need a hard drive I have in the office for this. I'll let you know as soon this are available.

**Comment by mgroglich** [comment]
Creating different issues for the different datasets
