### ISSUE TITLE
QGIS3 TypeError: 'int' object is not subscriptable python error

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#227]
When loading an existing TE dataset, the plugin returns a message stating "Trends.erath does not have a style assigned for *dataset*... To use this layer, manually add it your map". 
![OpeningTeLULC_PythonError1](https://user-images.githubusercontent.com/22821787/69682016-e3a16280-1064-11ea-9ca6-00432e8d2b02.JPG)
Then, when hitting OK, it returns a python error
![OpeningTeLULC_PythonError](https://user-images.githubusercontent.com/22821787/69681187-26ae0680-1062-11ea-917a-a0ef1c4fdf2c.JPG)

**Comment by azvoleff** [comment]
This first part of this isn't a bug - this is because we haven't defined styles for all of the various types of data you can download. So the message is correct. The second part, the Python error, definitely is a bug though - that should never happen. I'll look into it.

**Comment by gdaldegan** [comment]
this error is happening when trying to download raw data for 'SDG 15.3.1 Productivity Indicator (Trends.Earth)' and 'Soil organic carbon degradation'

**Comment by azvoleff** [comment]
Fixed.
