### ISSUE TITLE
TE for QGIS3 - Python error when calculating SOC

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#229]
Consistently getting a python error when trying to calculate Soil Organic Carbon when using a custom SOC layer
![SOC_PythonError](https://user-images.githubusercontent.com/22821787/70285175-789a0f00-177b-11ea-9c43-b1245caa6071.JPG)

**Comment by azvoleff** [comment]
@gdaldegan - is this still an issue?

**Comment by gdaldegan** [comment]
@azvoleff yep, just got the same Python error message

**Comment by azvoleff** [comment]
:(

**Comment by azvoleff** [comment]
I'll take a look.
