### ISSUE TITLE
trends zip download not compatible QGIS 3.4.8 GRASS

### ISSUE THREAD

**Issue by malcarazrios** [ConservationInternational/trends.earth#230]
Zip download for TRENDS on QGIS 3.4.8 is not loading. 
Maybe mention compatibility with QGIS 3.10.0 and older versions

**Comment by azvoleff** [comment]
@gdaldegan can you update the instructions page (readme.md) to make this clear? We only support QGIS 3.10 or greater.

**Comment by gdaldegan** [comment]
@azvoleff double checking on the QGIS version we currently support. You mentioned QGIS 3.10 or greater, but currently I'm using version 3.8.3-Zanzibar. Should we state the 3.10 or greater in our instructions page?

**Comment by azvoleff** [comment]
Yes, let’s stick with 3.10 or greater. 3.10 is a long-term release (LTR) so it will be maintained for a year, whereas 3.8 was only maintained until 3.10 came out in October – see the release schedule for QGIS here: https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule.

**Comment by gdaldegan** [comment]
edited 'README.md' file stating that TE is supported for QGIS 3 or greater versions. Also removed lines mentioning TE for QGIS2 and included a link to the 'releases' repository where users can download older versions
