### ISSUE TITLE
Add default styles for commonly used data downloads

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#232]
Right now there are no styles defined for datasets accessed with the data download tool so people get a error message telling them to add layers manually. It would be great though to either 1) get some simple styles defined, or 2) to add the layers with whatever default style QGIS assigns them (similar to what would happen if you just dragged and dropped the rasters in).

@gdaldegan can you look into this?

**Comment by azvoleff** [comment]
QGIS2 didn’t have a good way of manually defining styles for datasets that had varying limits (where stretches varied file to file, etc., so I took the approach of defining a number of different types of stretches, and categorical styles, and then defining the style for each layer in [styles.json](https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/data/styles.json). 


Styles are keyed to particular data files based on the type of file. The different types of files are all listed in [gee_datasets.json](https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/data/gee_datasets.json).

Any file type that is listed in gee_datasets.json, but not in styles.json will generate an error saying no style is defined. For QGIS 3 we could experiment with instead using style files - you can get these by adding a layer to QGIS, styling it, and then right clicking the layer and choosing "Export" -> "Save as QGIS Layer Style File...". For that to work you'd need to generate a style and export it for each data download type, and then key the names of the style files to data download types by adding a field to gee_datasets.json. Only problem with that approach is that we'd need to work out a way of translating the labels and titles in the style files.

**Comment by gdaldegan** [comment]
@azvoleff these are the layers throwing a KeyError:
- Soil Organic Carbon Degradation -> 'year_start' ('year_end'?)
- Land Cover Degradation ->'year_baseline'
- ESA CCI Land Cover ->'year_start' ('year_end'?)

**Comment by azvoleff** [comment]
@gdaldegan - I finally got around to trying to fix this today. I've updated the data_download code to save the metadata from the properties saved on the GEE assets. I see you added the year_start, year_end values, etc. to properties. But one complication: the names of each field have to exactly match what is used in [layers.py](https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/layers.py), including case (they are case sensitive). For SOC degradation, for example, they need to be "year_start" and "year_end", but right now they are saved in the GEE asset properties as "Start_Year" and "End_Year". Can you fix the property names for that and the other relevant layers so they match exactly?

**Comment by gdaldegan** [comment]
@azvoleff , thanks for looking into this and for the orientation. Will work on it tomorrow morning and make sure to align names in the styles file with the layers.py

**Comment by gdaldegan** [comment]
@azvoleff I've just edited the properties of relevant GEE assets (lc_traj_globe_2001-2001_to_2015 ; soc_globe_2001-2015_deg ; sdg1531_gpg_globe_2001_2015_modis ; sdg1531_lpd_globe_2001_2015_modis ; lp5cl_globe_2001_2015_modis) and downloaded those files that were triggering error messages (Soil Organic Carbon Degradation ; Land Cover Degradation ;
ESA CCI Land Cover) without any issue this time.

**Comment by azvoleff** [comment]
Awesome! Thanks for fixing this.
