### ISSUE TITLE
TE for QGIS 3 - Create Print Map error

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#233]
Hitting an error message when using 'Create Print Map' feature.
![CreatePrintMap](https://user-images.githubusercontent.com/22821787/71033972-38b51f00-20cd-11ea-9506-8a1c7ded03a2.JPG)

**Comment by azvoleff** [comment]
@gdaldegan can you look into this? Likely this is another QGIS2 - QGIS3 issue.

**Comment by gdaldegan** [comment]
as suggested by @azvoleff, I've modified the 'visualization.py' code to return a message stating "Coming Soon!" when clicking on 'Create Print Map', as this will most likely take sometime to figure out how to create a layout in QGIS3
