### ISSUE TITLE
Update CCI data

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#234]

**Comment by azvoleff** [comment]
@MLNoon - can you check with Mariano on this and when it is finalized post the new asset location here so I can update it in the tool?

**Comment by azvoleff** [comment]
@gdaldegan - is the 2019 CCI data available yet? Or is the 2018 the latest we have?

**Comment by gdaldegan** [comment]
@azvoleff land cover for for 2016--2018 is the latest update: https://www.esa-landcover-cci.org/?q=node/197

**Comment by azvoleff** [comment]
Thanks, awesome, so we're done here!
