### ISSUE TITLE
Check translation of layer names is occurring correctly

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#254]
@gdaldegan - can you check that the dialogs, and especially the layer names are showing up with correct Portuguese translations when the interface is set to Portuguese? (once you are done with the translations that is)

@mgroglich - can you check the same for Spanish?

You'll of course need to install from the zipfile (or with "invoke plugin-install") to get the latest.

**Comment by mgroglich** [comment]
Spanish translations done. The text in the menu looks good. But the layers are still in English (see image below). Also, there seems to be something weird with the way State is named.
![image](https://user-images.githubusercontent.com/18239218/78911098-d73a0700-7a53-11ea-8f34-7f084da48b63.png)

I noticed that we should fix the title (in English) for when we use the hansen dataset in the C tool, to "Percent tree cover to be considered forest" (it currently says forest both times).

![image](https://user-images.githubusercontent.com/18239218/78911265-1700ee80-7a54-11ea-899e-c25c196dbaeb.png)

**Comment by azvoleff** [comment]
I've fixed the forest tree cover text issue. State is actually correct in the above - it is referring to the periods used for comparison. I've changed "to" to "vs" - is that clearer? Now the above would read "Productivity state degradation (2001-2012 vs 2013-2015)".

Still looking into why the translated layer names aren't showing up correctly.

**Comment by azvoleff** [comment]
This should be fixed in 56c9960f251. Let me know if you still see issues.
