### ISSUE TITLE
Error installing plugin using QGIS v10.3.4

### ISSUE THREAD

**Issue by MLNoon** [ConservationInternational/trends.earth#255]
I get this when trying to install the plugin (as of 4/6/2020) 
![image](https://user-images.githubusercontent.com/19840094/78600942-e3d71900-7821-11ea-9e6e-ec172414a371.png)

**Comment by azvoleff** [comment]
@MLNoon - do you still get this error? and how are you installing it? zipfile or through the plugin manager? And what version of QGIS?

**Comment by azvoleff** [comment]
Sorry, I see the version is in the title - I assume you mean 3.10.4?

**Comment by MLNoon** [comment]
You are not using v10 yet? Yes, I meant v3. It seems to be working now. I had to go to the plugin manager and check the box next to the Trends.Earth plugin for the plugin to appear. When I first downloaded the zipped file and installed through the zip file option in Manage and Install plugins, I first received this error despite knowing the version of plugin and software were compatible.

**Comment by azvoleff** [comment]
Ok, I'll close this for now then, since it is working now, and as I have no idea why it didn't the first time,  no way I could try to fix it anyways :)
