### ISSUE TITLE
update merra2 soil moisture

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#267]
Gabriel, could you please update the merra2 soilmoisture in the code?

Old asset:
var image = ee.Image("users/geflanddegradation/toolbox_datasets/soilm_merra2_1980_2016");

Updated asset:
var image = ee.Image("users/geflanddegradation/toolbox_datasets/soilm_merra2_1980_2019");

**Comment by gdaldegan** [comment]
@mgroglich double checking the code which to modify. I'm about to substitute the asset in the second to last line in the code 'c06_soilm_merra2' within GEE account 'gef.land.degradation@gmail.com'

**Comment by mgroglich** [comment]
No, here: 
https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/data/gee_datasets.json

@azvoleff  could you please confirm.

**Comment by gdaldegan** [comment]
done!
