### ISSUE TITLE
Fixes to Portuguese translation

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#269]
Can you check the below links in the Portuguese translations? It looks like some of the link labels were translated but not the links, or vice versa, and like some of the RST syntax might have gotten thrown off by the translations. See the below message I am getting when I run `invoke docs-build -f -l pt`:

`reading sources... [100%] training/video_links
D:\Code\LandDegradation\trends.earth\docs\source\about\data_sources.rst:88: WARNING: inconsistent references in translated message. original: ['`CC by-SA 4.0`_'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\about\data_sources.rst:115: WARNING: inconsistent references in translated message. original: ['`Natural Earth Administrative Boundaries`_', '`public domain`_'], translated: ['`Domínio público`_']
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:616:<translated>:1: WARNING: Inline literal start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:616:<translated>:1: WARNING: Inline literal start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators11.rst:196: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-11-3-1-tutorial`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:117:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:117:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:117:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:117:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\documentation\settings.rst:55: WARNING: inconsistent term references in translated message. original: [':ref:`registration`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_compute_urban_indicator.rst:5:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_compute_urban_indicator.rst:5:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_compute_urban_indicator.rst:15: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-11-3-1-background`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_custom_soc.rst:10:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_custom_soc.rst:10:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_forest_carbon.rst:6:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_forest_carbon.rst:6:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_forest_carbon.rst:88: WARNING: inconsistent term references in translated message. original: [':ref:`task_download`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_forest_carbon.rst:121: WARNING: inconsistent term references in translated message. original: [':ref:`tut_load_data`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_run_all_subindicators.rst:8:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_run_all_subindicators.rst:8:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_task_download.rst:71:<translated>:1: WARNING: Inline strong start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] training/video_links
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:141:<translated>:1: WARNING: undefined label: indicador-produtividade (if the link has no caption the label must precede a section header)
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:156:<translated>:1: WARNING: undefined label: indicador-produtividade-trajetoria (if the link has no caption the label must precede a section header)
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:174:<translated>:1: WARNING: undefined label: indicador-produtividade-correção-clima (if the link has no caption the label must precede a section header)
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:215:<translated>:1: WARNING: undefined label: indicador-produtividade-performance (if the link has no caption the label must precede a section header)
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:227:<translated>:1: WARNING: undefined label: indicador-produtividade-estado (if the link has no caption the label must precede a section header)
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:280:<translated>:1: WARNING: undefined label: indicador-uso-da-terra (if the link has no caption the label must precede a section header)
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:366:<translated>:1: WARNING: undefined label: indicador-soc (if the link has no caption the label must precede a section header)
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:418:<translated>:1: WARNING: undefined label: indicador-15-3-1-combinando-indicadores (if the link has no caption the label must precede a section header)`

**Comment by gdaldegan** [comment]
will do

**Comment by gdaldegan** [comment]
checked and solved all warning messages.
