### ISSUE TITLE
Fixes to Spanish translation

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#270]
Can you check the below links/syntax in the Spanish translations? It looks like some of the link labels were translated but not the links, or vice versa, and like some of the RST syntax might have gotten thrown off by the translations. See the below message I am getting when I run invoke docs-build -f -l es:

`reading sources... [100%]
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:296:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:296:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:301:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:330:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:330:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:330:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:389:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:426:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:471:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:478:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:478:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:296:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:296:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:301:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:330:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:330:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:330:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:389:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:426:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:471:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:478:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:478:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:627:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\about\development.rst:8: WARNING: Undefined substitution referenced: "tendencias.earth".
D:\Code\LandDegradation\trends.earth\docs\source\about\faq.rst:224: WARNING: inconsistent references in translated message. original: ['productivity_'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\background\before_installing.rst:69:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\before_installing.rst:69:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\before_installing.rst:69:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\before_installing.rst:69:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators11.rst:179:<translated>:1: WARNING: Inline substitution_reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators11.rst:196:<translated>:1: WARNING: Inline substitution_reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators11.rst:179:<translated>:1: WARNING: Inline substitution_reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators11.rst:196:<translated>:1: WARNING: Inline substitution_reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:26:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:117:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:126:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:26:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:117:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\background\understanding_indicators15.rst:126:<translated>:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:141: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-productivity`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:156: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-productivity-trajectory`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:174: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-productivity-climate-correction`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:215: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-productivity-performance`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:227: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-productivity-state`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:280: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-land-cover`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:366: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-soc`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\documentation\calculate.rst:418: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-15-3-1-combining-indicators`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\documentation\gee_tasks.rst:6: WARNING: Undefined substitution referenced: "iconDownload".
D:\Code\LandDegradation\trends.earth\docs\source\documentation\settings.rst:55: WARNING: inconsistent term references in translated message. original: [':ref:`registration`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\index.rst:63: WARNING: Undefined substitution referenced: "tendencias.earth".
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_compute_sdg_indicator.rst:111: WARNING: inconsistent term references in translated message. original: [':ref:`tut_interpret_table`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_compute_urban_indicator.rst:233:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_compute_urban_indicator.rst:233:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_compute_urban_indicator.rst:233:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_compute_urban_indicator.rst:233:<translated>:1: WARNING: Inline strong start-string without end-string.
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_run_all_subindicators.rst:33: WARNING: inconsistent term references in translated message. original: [':ref:`indicator-15-3-1`'], translated: []
D:\Code\LandDegradation\trends.earth\docs\source\training\tutorial_summary_table.rst:16: WARNING: inconsistent term references in translated message. original: [':ref:`tut_compute_sdg`'], translated: []
looking for now-outdated files... none found
pickling environment... done`

**Comment by mgroglich** [comment]
All the issues addressed!
