### ISSUE TITLE
Error when trying to compute sdg 15 with custom sub indicators

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#271]
Cesar has been trying to run the analysis computing the 3 subindicators separately:
* productivity 2001-2019
* land cover 2001-2018
* soc 2001-2019

The subindicators run correctly, the error comes when trying to compute the SDG with these 3 layers after running for ~20 min. Sub-indicators available from link below:

https://www.dropbox.com/s/3ju0dqz2pzy9dv7/kazahstan_subindicators.zip?dl=0

Error:

An error has occurred while executing Python code: 

AttributeError: 'MergedCell' object attribute 'value' is read-only 
Traceback (most recent call last):
  File "D:/Documents and Settings/mgonzalez-roglich/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\calculate_ldn.py", line 863, in btn_calculate
    self.output_tab.output_basename.text() + '.xlsx')
  File "D:/Documents and Settings/mgonzalez-roglich/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP\calculate_ldn.py", line 1028, in make_summary_table
    cell.value = lc_totals[i][6]
AttributeError: 'MergedCell' object attribute 'value' is read-only

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.4-A Coruña A Coruña, 10bc9f2ff2 

Python Path:
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
D:\Documents and Settings\mgonzalez-roglich\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\LDMP\ext-libs
D:\working\temp\plugin_binaries\trends_earth_binaries_1_0_0\trends_earth_binaries_1_0_0
D:/Documents and Settings/mgonzalez-roglich/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/Documents and Settings/mgonzalez-roglich/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
D:/Documents and Settings/mgonzalez-roglich/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/Documents and Settings/mgonzalez-roglich/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LDMP

**Comment by azvoleff** [comment]
That's annoying... looks like it is failing on the last step! Looks like a problem writing to a cell in the summary file. I'll look into this.

**Comment by mgroglich** [comment]
I tried it with the one step data and it then worked fine. Also, Cesar said that the TIF and XLS files were created even though it gave an error... in case that info helps.

**Comment by azvoleff** [comment]
Fixed in 57e51e9.
