### ISSUE TITLE
Update GPCC precipitation data

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#274]
Gabriel, could you please update the precip dataset below?

Old asset:
var image = ee.Image("users/geflanddegradation/toolbox_datasets/prec_gpcc_1901_2016");

Updated asset:
var image = ee.Image("users/geflanddegradation/toolbox_datasets/prec_gpcc_1891_2019");

https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/data/gee_datasets.json

Also, please update the table with the dataset information to reflect that this is V6. We previously hosted V7, but that ones has not been updated and there are minor differences between the two.

**Comment by gdaldegan** [comment]
@mgroglich could please confirm this is the documentation with the table to be updated?
https://github.com/ConservationInternational/trends.earth/blob/master/docs/source/about/data_sources.rst

**Comment by mgroglich** [comment]
Yes, that is the table. Thanks.

**Comment by gdaldegan** [comment]
Done
