### ISSUE TITLE
Update GPCP precipitation data

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#275]
Gabriel, could you please update the precip dataset below?

Old asset:
var image = ee.Image("users/geflanddegradation/toolbox_datasets/prec_gpcp23_1979_2016");

Updated asset:
var image = ee.Image("users/geflanddegradation/toolbox_datasets/prec_gpcp23_1979_2019");

https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/data/gee_datasets.json

This is the same version as the previous one, so only updating dates.

**Comment by gdaldegan** [comment]
Done!
