### ISSUE TITLE
Productivity indicator performance and state only until 2015 

### ISSUE THREAD

**Issue by rkstan** [ConservationInternational/trends.earth#277]
Hi all, I am calculating productivity as part of indicator 15.3.1. Even though I specify the time period from 2001 to 2018 (MOD13Q1 NDVI trends), the state and performance metrics are still calculated only to 2015 whereas the trajectory takes into consideration the full time period until 2018. Any way you could extend the state and performance metrics to include the full time period? Thank you for your help!

**Comment by azvoleff** [comment]
You can the periods used for performance and state by using the "use customized data" option on the "Calculate Indicators" screen for 15.3.1. You'll see a page like this:

![image](https://user-images.githubusercontent.com/107753/82703033-283b3e80-9c41-11ea-9dcf-827038a0dff9.png)

On that page you can modify the dates used for state and performance. Is that what you are looking for?

**Comment by rkstan** [comment]
Yes, that's what I am looking for. I am sorry, I don't know how I missed it. Thank you for your help!
