### ISSUE TITLE
Python error when loading custom LC

### ISSUE THREAD

**Issue by MLNoon** [ConservationInternational/trends.earth#278]
![Captura](https://user-images.githubusercontent.com/19840094/82048381-9355a580-9682-11ea-9445-ff107f3eb3a4.JPG)
User receives a python error when loading custom land cover. Checking to see if the extent does not match admin boundary, but requires a different error message for useful troubleshooting.

**Comment by azvoleff** [comment]
I can get this one - just a typo in the syntax for the statement giving that error message
