### ISSUE TITLE
Rollbar error on productivity

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#285]
While running productivity - see: https://rollbar.com/azvoleff/trends.earth-API/items/31

Parameters:

{
  "ndvi_gee_dataset": "users/geflanddegradation/toolbox_datasets/ndvi_modis_2001_2019",
  "prod_state_year_tg_end": 2015,
  "prod_mode": "Trends.Earth productivity",
  "crosses_180th": false,
  "prod_state_year_bl_end": 2012,
  "calc_traj": false,
  "prod_state_year_tg_start": 2019,
  "climate_gee_dataset": null,
  "calc_state": true,
  "prod_traj_year_initial": 2001,
  "prod_traj_year_final": 2015,
  "geojsons": "[{\"coordinates\": [[[11.741535634861691, 45.53302885219975], [12.67280276013926, 45.53302885219975], [12.67280276013926, 46.08221344299599], [11.741535634861691, 46.08221344299599], [11.741535634861691, 45.53302885219975]]], \"type\": \"Polygon\"}]",
  "prod_perf_year_final": 2015,
  "ENV": "prod",
  "prod_perf_year_initial": 2001,
  "crs": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]",
  "task_notes": "",
  "trajectory_method": "ndvi_trend",
  "prod_state_year_bl_start": 2019,
  "task_name": "productivity_tv_e",
  "calc_perf": false,
  "EXECUTION_ID": "5b8d62e0-a041-4f92-a998-6daf8ff49f4d"
}

**Comment by azvoleff** [comment]
Oh, looks like another one where the state year end is before the state year start - need to add a check for this into the toolbox to ensure the dates are consistent

**Comment by gdaldegan** [comment]
I suspected that, given the error message was exactly the same as from the issue triggered a couple weeks ago.
I’m about to finish addressing the Mariano’s final comments on the report and will look at the issues you’ve assigned me.

**Comment by azvoleff** [comment]
Closing as no longer visible in rollbar
