### ISSUE TITLE
AttributeError: 'AOI' object has no attribute 'l'

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#293]
getting an error message when trying to calculate SDG1531 for the 'Bogota Conservation Corridor' shapefile (attached)
![AttributeError_AOI object has no attribute l](https://user-images.githubusercontent.com/22821787/88726441-b9c0a400-d0fb-11ea-9449-13ddb1c45504.png)

[Bogotá_Conservation_Corridor.zip](https://github.com/ConservationInternational/trends.earth/files/4991369/Bogota_Conservation_Corridor.zip)

**Comment by azvoleff** [comment]
1006 just means it is a multipolygon with Z coordinate. Need to broaden what we consider valid datatypes since we don't care if it has a z coordinate. If you drop the z coordinate it should process fine.
