### ISSUE TITLE
Make list of all fields that we will return to LandPKS from our API (png file URLs, information fields, title fields, etc.)

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#310]

**Comment by mgroglich** [comment]
Based on the data that we have, some of the starting and end years are different, how should we address this?

**Comment by azvoleff** [comment]
We do it directly in the code - [see here for example](https://github.com/ConservationInternational/trends.earth/blob/master/gee/landpks/src/main.py#L344). I can explain on our call today.
