### ISSUE TITLE
Name raster bands to be self explanatory 

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#322]
When trends.earth results are loaded into QGIS using the tool the bands display names using metadata in the Json, let's please also hardcore into the code (in the GEE section) a "rename" statement to make sure simple to understand names are embedded into the tif so that they also display when loading rasters in QGIS without using Trends.Earth or in ArcGIS.

**Comment by azvoleff** [comment]
Yeah this is annoying. And unfortunately getting this to work consistently is more complicated than it seems - the GeoTIFF standard doesn't include band names, so they aren't uniformly supported across software. Getting them to work from GeoTIFF files is hit or miss - it just happens that the GEE names DO work in ArcGIS. They don't work well though in GDAL, R, and a lot of other software, and as we use GDAL locally in QGIS for most of the file input/output, we can't retain band names when we save files from the plugin (so the SDG layers, etc.). 

The other problem is the need to translate the band names. For this reason the band names themselves (in terms of what you see as band titles in QGIS) aren't used in the GEE code. What are used are the band tags (the top-level names in this file: https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/data/styles.json). Those are then used as keys to pick the right translation depending on the QGIS language settings.

What might work would be to keep the tags as we do now, but then generate a header file in QGIS for each download, which could then probably work to have names show up in ArcGIS (with the caveat that it would only work if users moved all the files together before loading them). But if this did work then it would have the advantage of working for both downloads from GEE and also for files we generate, while also allowing us to generate the names in the correct language.

**Comment by mgroglich** [comment]
How about something simple at least like "b1, b2, b3... etc" (right now they are all over) which we don't even need to translate, but which at least we can then refer to on the website?

**Comment by azvoleff** [comment]
Sure, we can add it - we just need to remember those names may or may not show up reliably for users if we are just adding them through the GEE code, so we can't really rely on it as a longer-term solution.

**Comment by azvoleff** [comment]
This could be a solution: https://en.wikipedia.org/wiki/Styled_Layer_Descriptor. Do you happen to know if those are supported in ArcGIS?

**Comment by azvoleff** [comment]
And if that file type would work it would be awesome, since we could also share styling information across QGIS and Arc, and do away with the hacky JSON files we are using right now.

**Comment by azvoleff** [comment]
Hmm, looks like using that file type could work. But we couldn't have all the styles in one style file given we have multiple raster layers stored within a single geotiff. So no clean way to load the layers with styles in ArcGIS the way we do with our import tool in QGIS. But we could provide multiple sld files that would then allow loading the layers in Arc or other software supporting that type of style file (as well as in QGIS). Let's save this one for when we start making changes in advance of the next round of reporting

**Comment by azvoleff** [comment]
Also see #217.

**Comment by azvoleff** [comment]
Addressed in latest versions
