### ISSUE TITLE
Cannot download results from Earth engine

### ISSUE THREAD

**Issue by au590486** [ConservationInternational/trends.earth#325]
Hi 
I have calculated the three subindicators using the trends.earth plug-in in QGIS 2.18. 
The status is displayed as 'READY' but whenever I choose one of the files for download the 'downlad results' button stays inactive. 

I hope you can help me access the file.

Best

**Comment by azvoleff** [comment]
We need to update our site to reflect this, but we have now released a version for QGIS 3. We have moved all development now to that version. Can you please try running this in the latest version of QGIS (now 3.16), with the latest version of the plugin, and let us know if you still see an issue?
