### ISSUE TITLE
Update trends.earth website

### ISSUE THREAD

**Issue by MLNoon** [ConservationInternational/trends.earth#326]
Update language for this text if v2.18 is no longer working. Can we remove this from the QGIS plugins so that people do not run using v2.18 any longer?:

What version of Quantum GIS (QGIS) do I need for the toolbox?
To download QGIS, please go to the QGIS Downloads page. As of February 2018, version 3.0 was released. Please use version 2.18 for the trends.earth plugin. A version compatible with the latest version will be released in future iterations of the project.

**Comment by azvoleff** [comment]
No longer relevant
