### ISSUE TITLE
Add WorldPop and other pop datasets into datasets tab within tool

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#336]
Once we have them added as assets, and then added in the JSON datasets file so they show up in the download tool, it will be easy to use them in the future within any subsequent reporting tasks.

@gdaldegan - since this is an assets issue, can you add them? We'll need to verify the WorldPop license first to ensure we can redistribute. I think it is Creative Commons so we should be ok, but need to check to make sure.

**Comment by gdaldegan** [comment]
checked WorldPop license: "WorldPop datasets are licensed under the Creative Commons Attribution 4.0 International License. Users are free to use, copy, distribute, transmit, and adapt the work for commercial and non-commercial purposes, without restriction, as long as clear attribution of the source is provided"
