### ISSUE TITLE
Review existing resources

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#344]
Review the following:

- [Minimum data quality standards and decision trees for SDG Indicator 15.3.1](http://earthobservations.org/documents/ldn/20200703_GEOLDN_TechnicalNote_FINAL_SINGLE.pdf) document.
- Trends.Earth QGIS plugin (this repo) - be sure to install the plugin locally. Explore it and get comfortable with the source code

Think about how the decision trees presented in the document may be implemented in the QGIS plugin. We will be scheduling a meeting in the coming week to put our heads together and come up with a design and implementation plan, so this is your homework for that meeting :wink:

**Comment by luipir** [comment]
@ricardogsilva what metric do you use to define size? I'm used to use fibonacci serie 0,1,2,3,5,8,13,... https://en.wikipedia.org/wiki/Fibonacci_scale_(agile) usually 20 is a really BIG and complex task

**Comment by ricardogsilva** [comment]
> what metric do you use to define size?

This is some custom metric we are using internally. I don't really know what was the motivation for its creation nor was I involved in it. (FWIW I've also used fibonacci-based scales in the past).

Check the label's description for the meaning of the various points.
