### ISSUE TITLE
Update land cover dataset in code (to include 2019)

### ISSUE THREAD

**Issue by mgroglich** [ConservationInternational/trends.earth#348]
Replace current dataset (lcov_esacc_1992_2018) by "lcov_esacc_1992_2019".

"users/geflanddegradation/toolbox_datasets/lcov_esacc_1992_2019"

 Also allow for 2019 in the GUI.

**Comment by gdaldegan** [comment]
updated path to new dataset and the 'End year' to 2019 in the 'gee_datasets.json' file
