### ISSUE TITLE
Redesign user and authentication management

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#354]
According with the implementation plan, the Settings section shall be redesigned to look like the below mock-up

![geo-ldn-issue-settings-auth](https://user-images.githubusercontent.com/732010/107041969-11ca1880-67b9-11eb-9dc1-4847f313aa9c.png)

Please also note the new **test connection** button, which did not feature in the original design

Implement the section that deals with user and authentication management so that both the GUI and the underlying code reflect the above vision.

### Notes

- Authentication credentials shall make use of QGIS authentication infrastrcuture
- All remaining settings shall be stored in `QgsSettings`. Use `trends_earth` as the base setting key
- `Register new user...` button shall reuse the already existing dialogue
- `Manage user account...` button shall lead to a new dialogue that combines the features currently shown by both the `Update account` and `Reset password` dialogues
- `Test connection` button shall allow the user to perform a quick connection to the GEE server to verify if the credentials are correct - Please use a [QgsMessageBar](https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/communicating.html#showing-messages-the-qgsmessagebar-class) attached to the settings dialogue for providing feedback to the user on the status of the connection test

**Comment by luipir** [comment]
great tnx @ricardogsilva

**Comment by luipir** [comment]
started GUI refactoring in this branch https://github.com/luipir/trends.earth/tree/setting_refactory_354
in this moment it's just cosmetic leaving all old working functionalities (I hope)

**Comment by luipir** [comment]
@ricardogsilva @Samweli tehre is already a working version of the setting using auth system, please give a try.
I still have to solve problems of authSelect GUI that is not updated when an auth configuration is removed e.g. when the user delete his account or when register that the auth configuration is added automatically (without pwd).
Do you know how to trigger refresh of the authselect widget (seems a bug)
