### ISSUE TITLE
Redesign plugin menu

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#355]
According with the implementation plan, the plugin menu shall be redesigned to look like the below mock-up

![geo-ldn-issue-plugin-menu](https://user-images.githubusercontent.com/732010/107042751-01666d80-67ba-11eb-8016-7c86dce0fac4.png)

Please implement these changes

**Comment by luipir** [comment]
draft and working GUI already in https://github.com/luipir/trends.earth/tree/gui_refactoring
