### ISSUE TITLE
Redesign plugin toolbar

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#356]
According with the implementation plan, the plugin toolbar shall be redesigned to look like the below mock-up

![geo-ldn-issue-plugin-toolbar](https://user-images.githubusercontent.com/732010/107043173-8a7da480-67ba-11eb-9900-6b43bd4bf808.png)

As a provisional measure, since we have not implemented the other parts of the design yet, please also include in the dropdown icons for opening the dialogues for the other sections (calculate indicators, view google earth engine tasks, etc.). Otherwise it becomes impossible to use the plugin

**Comment by luipir** [comment]
draft and working GUI already in https://github.com/luipir/trends.earth/tree/gui_refactoring

**Comment by luipir** [comment]
> As a provisional measure, since we have not implemented the other parts of the design yet, please also include in the dropdown icons for opening the dialogues for the other sections (calculate indicators, view google earth engine tasks, etc.). Otherwise it becomes impossible to use the plugin

I'm not sure thi is practical... the old plugin can be installed from repo or from master branch... having a mix of previous code and new one is an overhead. Is it really necessary @ricardogsilva ?
