### ISSUE TITLE
Implement Advanced parameters in the Settings dialogue

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#359]
According with the implementation plan, the Settings section shall be redesigned to look like the below mock-up

![settings-dialogue](https://user-images.githubusercontent.com/732010/107291838-b5892200-6a60-11eb-9a32-c0af87dba2f8.png)

Implement the *advanced* section so that both the GUI and the underlying code reflect the above vision.

### Notes

- Take heed of the notes shown on the mock-up, to the right of the dialogue.
- If needed, review the initial proposal document (which is not being shared publicly for now)
- Store these settings in `QgsSettings`. Use `trends_earth` as the base setting key
- The `base data directory` setting shall be used by all algorithms as the root for data storage. Make sure this is also implemented in each algorithm's code. We want this plugin to keep working as we introduce the changes

**Comment by luipir** [comment]
@ricardogsilva @Samweli I've some concern about how to apply "base_data_directory" in the actual code trying to avoid to change workflow.
Any process use "LDMP/output_dir" as base from with a user can select the generated result... BUT if the user select another location, "LDMP/output_dir" is set to that location:
e.g. in https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/calculate_lc.py#L189 (and other parts of every calculate_*.py
That means general setting "LDMP/output_dir" or the new setting "trends_earth/advanced/base_data_directory" is possible overrided from any process or GEE download data.
How to proceed? base_data_directory would be the default start point (forgotting latest saving path?) ?

**Comment by ricardogsilva** [comment]
I think we should modify these other places where the UI is currently giving the user a chance to select another output directory in order to not let that happen anymore. 

Lets make it so that all plugin outputs are always and exclusively saved into some (sub-)dir inside the directory that has been set in the `trends_earth/base_data_directory` setting.

Taking it even a step further (as was described in our proposal) lets come up with an automatic naming scheme for all outputs, making it so that the user is not asked to choose a name for them. I think we will need to think about this in order to come up with something robust. Maybe something like:

```
{base-dir}/outputs/{algorithm-group}/{algorithm-name}/{algorithm-name}_{region-of-interest}_{creation-date}_{execution-number}.{file-format}
```

Which could translate to something like:

```
/home/ricardo/trends-earth/outputs/sdg-15-3-1/land-productivity/land-productivity_portugal-lisboa_202102181230_1.tif
```

This suggestion seems reasonable for an initial implementation. Would you agree @luipir ?

**Comment by luipir** [comment]
> I think we should modify these other places where the UI is currently giving the user a chance to select another output directory in order to not let that happen anymore.
> 
> Lets make it so that all plugin outputs are always and exclusively saved into some (sub-)dir inside the directory that has been set in the `trends_earth/base_data_directory` setting.

I agree is it fit their use case... can we check it out during next client meeting or we go forward with the "locked" naming convention?

**Comment by luipir** [comment]
In this moment I'll limit the functionality to lock the output folder... IMHO we should add a new feature request to prioritize locked naming convention. @ricardogsilva are you agree or you want I do all modification related with output naming conventions?

**Comment by luipir** [comment]
> {base-dir}/outputs/{algorithm-group}/{algorithm-name}/{algorithm-name}_{region-of-interest}_{creation-date}_{execution-number}.{file-format}

@ricardogsilva about this proposal and especifically to {region-of-interest} do you mind we have to introduce a set of ROI names that the user can select (kind of ROI profiles). In other way shouldn't be clear how to specify ROI becaus can be a mix of country-region-city or point location or vector . any opinion?
As you talked in the today meeting probably can be introduced (later) a ROI profile => i would skip {region-of-interest} in this phase.

**Comment by ricardogsilva** [comment]
IMO introducing a name for each region of interest would be undesirable, as it forces the user to do some extra work.

The user is currently able to choose the desired region of interest by selecting from one of four options. I think we can come up with a suitable naming fragment from each of these that we can use for naming output files. 

An initial suggestion:

1. User selects a ROI made up of a country and region - we can use `{countryname-regionname}`. Example: `portugal-lisboa`
2. User selects a ROI made up of a country and city - we can use `{countryname-cityname}`. Example: `spain-bilbao`
3. User selects a point - we can use `pt-lon{longitude}lat{latitude}` - we would use the point coordinates in EPSG:4326. Example: `pt-lon-19.345lat-22.444` (in this example both lon and lat are negative)
4. User selects an arbitrary shape given by a vector layer - we can use `shape-lon{centroidlongitude}-lat{centroidlatitude}` - we would use the coordinates of the shape's centroid, in EPSG:4326. Example: `shape-lon21.567-lat-176.123` (in this example only the centroid's latitude is negative)
