### ISSUE TITLE
Add plugin dock UI

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#366]
As discussed previously, we are introducing a dock area as the main plugin widget. 

![geo-ldn-plugin-dock](https://user-images.githubusercontent.com/732010/108715462-d3e82680-7512-11eb-9cfa-8d57bc0a8c24.png)

As seen in the mockup above, the dock shall use a tab widget with two tabs, named _Algorithms_ and _Datasets_. This issue deals only with the creation of the dock, tab widget and the two tab pages. The contents of each tab are not in scope here (they shall be handled in other issues)

### Notes
- The dock shall be enabled/disabled by the user pressing the main plugin icon (make it checkable)
- It shall be put on the right side of the main QGIS UI

**Comment by luipir** [comment]
starting to check similar GUIs to inspire the code

**Comment by luipir** [comment]
I've to read better the issue... now I figureout that the issue was only about the dock and not about the content
