### ISSUE TITLE
Implement automatic download of remote datasets

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#376]
Whenever a remote algorithm finished execution its outputs become ready for download. The default behavior for Trends.Earth shall be to proceed to download them automatically.

Foreseen workflow is:

- A refresh of the datasets list is initiated (either automatically or by request of the user)
- Datasets that are in a `being generated` state are checked to discover whether they are ready to be downloaded
- trends.earth proceeds to download datasets that are ready, updating their state accordingly

Downloading a dataset shall be made in a background task, in order to prevent locking up the QGIS main UI and allow the user to carry on with other work.

Additionally we shall allow this automatic download behavior to be disabled by the user. This shall be tracked in #373 and is not in scope for this issue.

**Comment by luipir** [comment]
almost implementes... now I've the problem that a downloaded dataset has a json descriptor (almost but not complete similar to the original dataset) that is parsed as Dataset => I've to find a criteria to discriminate them avoiding to create a dataset instance for them (that generate errors)
Or I've to remove the original dataset descriptor when a downloaded dataset descriptor is availabl?
I've to check what is the best and correct solution.

p.s. there is a set of implementation problems born from the fact to separate job and dataset entities

**Comment by luipir** [comment]
almost done in branch https://github.com/luipir/trends.earth/tree/datasets_download_rebased
now I've to configure to start automatic download when status if completed

**Comment by luipir** [comment]
about background task (almost) nothing is changed and the download is managed in background as before.
The only change is to check if data has been already downloaded. Before there a check only in case of tiles.

**Comment by luipir** [comment]
impleenter (no idea why issue is not closed automatically)
