### ISSUE TITLE
Modify algorithms tab in order to not have three hierarchic levels

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#396]
Navigating the algorithms tab section is currently a bit cumbersome due to the 3 levels of nesting we are using. Modify it to have just two levels:

- first the algorithm groups
- then each algorithm

Here is a mockup of what it would look like:

![geo-ldn-dock-algorithms-tab-two-levels](https://user-images.githubusercontent.com/732010/116724038-0eb97f80-a9d8-11eb-9b25-11ad128183d3.png)

**Comment by luipir** [comment]
working in this branch https://github.com/luipir/trends.earth/tree/reduce_alglist_tree_%23396
