### ISSUE TITLE
Implement filtering the list of existing datasets

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#400]
The dataset list currently has a text box that shall be used to filter existing datasets. Filtering shall be done on a dataset's **name**.

Ideally this filtering should be done as the user is typing, _i.e._ without having to include another button on the UI to enable the filter string.

This may be implemented with [QSortFilterProxyModel](https://doc.qt.io/qt-5/qsortfilterproxymodel.html)

**Comment by luipir** [comment]
closed via https://github.com/ConservationInternational/trends.earth/commit/8025f095b630dd74bf50a31816dffc1002524d7f
