### ISSUE TITLE
Allow deleting a dataset

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#403]
Each item in the datasets list shall show a `delete` button and pressing it shall ultimately result in the dataset being deleted from the local filesystem. This action needs to be guarded by an additional confirmation dialog, where the user must confirm the intention of having the dataset be deleted.

The action of deleting a dataset must result in the deletion of:

- The actual dataset
- The json sidecar file that we are using to store the dataset details

### NOTE

The `delete` button should only be enabled for datasets that are available locally.

**Comment by luipir** [comment]
@ricardogsilva FYI at this moment, datasets list is guided by the list of jobs downloaded via API (/etxecutions) => if a datasets is deleted, it can be created again IF it appear in the list of Jobs.
The only way to change this behaviour is to maintain a list of deleted datasets. IMHO we should remain with the stateless REST logic.

**Comment by ricardogsilva** [comment]
Do you mean that it would be impossible to delete a dataset while it is still being reported as available on the remote server? - That doesn't seem very intuitive. It would mean the user would only be able to delete a dataset after the remote has cleared the list of recent jobs.

I agree with you that keeping a list of deleted datasets is not ideal. However, I don't see another way to overcome this situation.

We will also need to know about the datasets that have already been downloaded, in order to avoid re-downloading them. This is a somewhat similar situation.

With this in mind. I propose having a local registry of datasets where this information shall be kept. Each dataset shall have some unique identifier, so we can use that to update our local registry with this information. We will keep track of which datasets have been downloaded and if they are deleted locally.

If a user chooses to delete a dataset we do not want Trends.Earth to automatically re-download it the next time it syncs with the remote server.

do you agree @luipir ? Or do you have some alternative proposal?

**Comment by luipir** [comment]
I wouldn't overcomplicate something that is not user demanded. If they lived without a way to remotely delete a dataset => better to avoid to enter in a set of use cases when we have only 1 month to end.

> We will also need to know about the datasets that have already been downloaded, in order to avoid re-downloading them. This is a somewhat similar situation.

this is already managed by the original code... that do not download any generated product if it is already locally available:
https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/jobs.py#L427

> If a user chooses to delete a dataset we do not want Trends.Earth to automatically re-download it the next time it syncs with the remote server.

thsi open another usecase... if you delete dataset erroneously locally you need a way to recover this situation => opening again another set of usecases.

my proposal is keep it simple! seems the user do not case os this border cases because used to live with a stateless API oriented system.

the workflow would be:
1) Show always datasets available (in a timewindow)
2) do not show dataset if downloaded (e.g. show only it's downloaded contrepart)
3) if user remove dataset locally => it become again available to download (they do not have any API to remove remote datasets/jobs). Note it is available for download only if it's job is still available in the query time window

**Comment by ricardogsilva** [comment]
> If they lived without a way to remotely delete a dataset => better to avoid to enter in a set of use cases when we have only 1 month to end.

Perhaps I didn't make myself clear - I am not saying we need to delete datasets on the remote server.

What I am saying is that there are two requirements for this functionality:

1. Users need a way to delete local datasets;

2. We do not want to re-download datasets that the user has chosen to delete, as that would be confusing. The user would need to know that sometimes a dataset can be re-downloaded (because the server still shows it in the recent jobs list) but sometimes the dataset can no longer be re-downloaded.

---

The use case of a user deleting a dataset erroneously is not a good justification for not providing the functionality. As stated in the issue description we will even add a confirmation dialog to help prevent this type of error. If the user still manages to delete a dataset by mistake then the user will need to re-generate the dataset again.

I guess you can think of it like this: there is a 1:1 mapping between a job and its result. In reality we do not care about the job so much. We care about the result. When the job is running, we obviously do not have the result yet, so we need to track the job's execution status in order to know when we will be able to retrieve the underlying result. 

When the job is done we get the result. At this stage, for our purposes we do not care about the job anymore. This means that if a dataset is removed by the user then we need to start a new job if we want to get a similar dataset again.

---

> my proposal is keep it simple! seems the user do not case os this border cases because used to live with a stateless API oriented system.

The old way was kind of opposite of this: Trends.Earth showed a list of jobs to the user and it was possible to get a job's result. The new way is different: Trends.Earth now shows a list of results to the user and the underlying job is more of an implementation detail. 

We are now focusing on the actual datasets instead of focusing on the jobs that generate them. IMO this is more user-centric, as the user cares about results, not so much where/how they are generated.

So yeah, before there was no need to delete a job. But now there is a need to delete a (local) dataset.

Also, please note that even though the API is stateless, state is still kept on both sides (server and client). And this was the fact in the previous version of Trends.Earth too. The client kept the local datasets on disk and it would check them to decide whether to re-download or not - this is keeping state. The difference is that it was not possible to delete a local dataset before and we are now adding this as a feature.

---

I am not introducing any new use cases other than what we originally proposed. I am also not trying to complicate your work, quite the opposite. I don't have a strong opinion on the actual technical implementation and will accept mostly anything that works.

I suggest keeping a local registry of a dataset's state but I'm open to alternative solutions. If you can think of a nicer way to meet the requirements I stated above, I am all for it.

What it seems to me that you are getting at is that you think we should not implement this feature because of the complexity and time constraints involved. Is this correct? If so, then I think we can decide to not implement dataset deletion. We just need to communicate that openly.

**Comment by luipir** [comment]
> 1. Users need a way to delete local datasets;

perfect



> 2. We do not want to re-download datasets that the user has chosen to delete, as that would be confusing. The user would need to know that sometimes a dataset can be re-downloaded (because the server still shows it in the recent jobs list) but sometimes the dataset can no longer be re-downloaded.

e.g if locally removed SHOULDN'T BE SHOWN again, nor if it's still possible to download it?

**Comment by ricardogsilva** [comment]
> e.g if locally removed SHOULDN'T BE SHOWN again, nor if it's still possible to download it?

yes, if locally removed, then it is gone forever!

Only way to get back a dataset that has been locally removed shall be to re-run the same algorithm with the same execution parameters and then get back a new dataset that is similar to the one that got deleted.

**Comment by luipir** [comment]
> Only way to get back a dataset that has been locally removed shall be to re-run the same algorithm with the same execution parameters and then get back a new dataset that is similar to the one that got deleted.

ok, this can simplify... jus move json descriptor in deleted and check if is there when getting job. Any job/dataset/downloaded dataset share the same UUID in the filename

**Comment by luipir** [comment]
working in this branch https://github.com/luipir/trends.earth/tree/dataset_delete

**Comment by luipir** [comment]
related PR https://github.com/ConservationInternational/trends.earth/pull/416

**Comment by luipir** [comment]
rebasing on latest merge in decision-tree

**Comment by luipir** [comment]
fixed via https://github.com/ConservationInternational/trends.earth/commit/04e7dab81eb507bb8c86942f23375731f80e0186
