### ISSUE TITLE
Implement dataset details dialog

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#407]
Each dataset shall have a dedicated dialog where all of its known details are shown to the user. This shall list:

- Details related to the dataset (name, creation date, etc)
- Details of the algorithm that produced the dataset (algorithm parameter values, etc)
- Notes written by the user upon configuring the algorithm

The dataset dialog shall also feature some buttons to perform dataset-related actions:

- Load dataset onto QGIS canvas
- Delete dataset
- Export dataset report (as discussed on #388)

The below mockup shows initial design for this dialog

![geo-ldn-dataset-detail-dialogue2](https://user-images.githubusercontent.com/732010/116892212-816c6a00-ac27-11eb-9b9a-d2c684e0df6d.png)

**Comment by luipir** [comment]
@Samweli I warn you to take into account locally generated datasets in case have to be shown in Dataset Details interface.
a JSON file genrated for a local process can have this form (but not sure if it is the only schema generated for local generated dataset)

```
{
    "bands": [
        {
            "activated": true,
            "add_to_map": false,
            "metadata": {},
            "name": "SDG 15.3.1 Indicator",
            "no_data_value": -32768.0
        },
        {
            "activated": true,
            "add_to_map": false,
            "metadata": {},
            "name": "SDG 15.3.1 Productivity Indicator",
            "no_data_value": -32768.0
        }
    ],
    "file": "8c7637b2-77d0-44f6-a7b5-da015ec996b2.tif",
    "metadata": {
        "task_name": "gen_final1",
        "task_notes": ""
    }
}
```
