### ISSUE TITLE
Trends.Earth crashes QGIS sometimes

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#408]
There seems to be some event related to Trends.Earth that sometimes causes a crash in QGIS. I've not been able to pinpoint the root of the problem nor am I able to reproduce it consistently.

@luipir is aware of the issue and has done some initial work around it.

**Comment by luipir** [comment]
investigating... btw I do not have crash since time... probably thanks to locks I introduced times ago

**Comment by luipir** [comment]
I can't replicate nomore :/ probably solved with the locks I added accessing Datasets() and Jobs() memory stores. IMHO can be lcose @ricardogsilva

**Comment by ricardogsilva** [comment]
I have also been unable to replicate this for about three weeks now. Closing.
