### ISSUE TITLE
Implement scanning of the local base dir in order to populate the datasets section

### ISSUE THREAD

**Issue by ricardogsilva** [ConservationInternational/trends.earth#409]

**Comment by luipir** [comment]
Probably we should avoid to update Jobs and Dataset asyncronously... or we should add a lock to avoid datasets created when the job store is updated.
A simplified solution is the unique refresh for both jobs and datasets (as it is now).
Do we really need a different refresh between jobs and datasets @ricardogsilva ?

**Comment by ricardogsilva** [comment]
My two requirements regarding this are:

1. Avoid locking up the QGIS GUI while doing potentially expensive IO operations
2. Make it possible to control (and even disable) the frequency of checking the remote server while making sure that the frequency of checking the local base dir is never changed (nor disabled)

I will be OK with the actual technical solution, as long as it is able to meet the above requirements.

---

Thinking a bit about it, I guess we should also explicitly trigger a refresh of the local datasets (_i.e._ an additional check, outside of the normal periodic checks) list when:

- One of the local algorithms finishes execution. 
- The download of a dataset finishes

This shall help achieving a lower latency as to when a dataset appears on the list after being available. 

I don't really see a need for using locks in this case. The scan of the base dir shall be looking for JSON files and parsing their content in order to read the dataset's `status` (we don't need to scan for the actual geotiff files nor do we need to wonder if the download is finished or not). If the JSON file reports that the dataset is available, then we put that dataset in our list as being loadable. Otherwise, the dataset's status shall report if the dataset is still being generated or being downloaded, and in that case we put it on the list as not being available.

**Comment by luipir** [comment]
> * One of the local algorithms finishes execution.

still have to check if all works with local process :/

**Comment by luipir** [comment]
local process is done correctly now:
implementatuion in branch https://github.com/luipir/trends.earth/tree/local_calculation

BTW generate results e.g. local generated dataset have (yet another) json format => need to manage (yet another) exception to allow visualize them in Dataset list.

@ricardogsilva what would be the expected way to manage locally generated datasets? e.g. what to show in Dataset list? what funcion have to be available? Add to canvas? dataset details? 
About Dataset details I would warn @Samweli to take into account this other type of dataset in case have to be shown in Dataset Details interface

**Comment by luipir** [comment]
I leaved it open becase we still have to manage get of datasets generated by local processing

**Comment by luipir** [comment]
wating for merge of https://github.com/ConservationInternational/trends.earth/pull/430 to close the issue

**Comment by luipir** [comment]
implemented via https://github.com/ConservationInternational/trends.earth/commit/8c42b4a416bc2afe14b41c61ba53998bd2f33864
