### ISSUE TITLE
Iinstallation of the plugin in QGIS 3.18 not working

### ISSUE THREAD

**Issue by YG1975** [ConservationInternational/trends.earth#411]
Hello,
I am using Mac (version 11.2.3 Big Sur) and want to use the plugin. However, even after re-installing QGIS with the latest version (using https://www.kyngchaos.com/software/archive/ to have all the proper frameworks), the plugin still can not be installed (see screenshot for more details). I have a similar issue with another plugin called "wps client". 

I am not sure what else I can do since I totally-de-installed and re-installed QGIS as I was having the same issue on previous 3.x versions, even though it was working well at the end of last year. Might it be linked to Big Sur?

Thank you in advance for your help.

![image](https://user-images.githubusercontent.com/12274266/117149128-33866c00-adb7-11eb-81e5-44d9456b834c.png)

**Comment by tz2436** [comment]
Hi, I am having the same issue. Looking for a workaround. Thanks

> Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method 
> 
> RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. If using conda try: #> conda install clang_osx-64 clangxx_osx-64 
> Traceback (most recent call last):
>   File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 49, in classFactory
>     from LDMP.plugin import LDMPPlugin
>   File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 24, in 
>     from LDMP.download_data import DlgDownload
>   File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/download_data.py", line 30, in 
>     from LDMP.calculate import DlgCalculateBase, get_script_slug
>   File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 59, in 
>     from LDMP.calculate_numba import *
>   File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate_numba.py", line 9, in 
>     cc = CC('calculate_numba')
>   File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/pycc/cc.py", line 65, in __init__
>     self._toolchain = Toolchain()
>   File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/pycc/platform.py", line 78, in __init__
>     self._raise_external_compiler_error()
>   File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/pycc/platform.py", line 121, in _raise_external_compiler_error
>     raise RuntimeError(msg)
> RuntimeError: Attempted to compile AOT function without the compiler used by `numpy.distutils` present. If using conda try:
> 
> #> conda install clang_osx-64 clangxx_osx-64
> 
> 
> Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
> QGIS version: 3.18.1-Zürich Zürich, 202f1bf7e5

**Comment by christiankaiser** [comment]
These 2 issues are not the same. I had the 2 of them (and a 3rd one documented in issue #318) with QGIS 3.16.8 on macOS 10.15.7, and Python 3.8.7, and the 'ascii' codec issue also with QGIS 3.20.0 and Python 3.8.7.

For the second issue above (RuntimeError: Attempted to compile AOT function without the compiler) you need to install xcrun using `xcode-select install` from Terminal which will install the compiler needed to install the plugin.

I was able to work around the first issue above ('ascii' decode problem) with the following steps (not all of them might be required but I am not sure which ones are):

- In QGIS Preferences, «General», activate «Override System Locale» and chose as «User interface translation» «American English» (or whatever language you want QGIS to be in)
- In the same place, chose a Locale («German Switzerland» in my case)
- In the «System» tab, in the «Environment» section, add a new variable «LANG» with value «en_US.UTF-8» (with «Overwrite» in the dropdown menu)

Once these step done, the plugin did load correctly.

To me, this issue does not seem to be related to the plugin itself, but rather to the QGIS installation, especially the way the locale is defined. The output of the `locale` command in the Terminal was:

```
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

However I am not sure to what extent this might help. If needed, I can make further tests or give more explanations.

**Comment by cmzambranat** [comment]
I can confirm that  @christiankaiser solution works! The third step (add new variable) was necessary. Thanks!

**Comment by azvoleff** [comment]
Adding @gabrieldaldegan to this thread as the resident Mac user on the trends.earth team. Can you confirm the above fix works for you on your machine? Looks like we might need to send the above to the core qgis team as [this one](https://github.com/ConservationInternational/trends.earth/issues/411#issuecomment-872472962) at least doesn't seem to be a plugin issue

**Comment by tz2436** [comment]
Thanks @christiankaiser 
I did `xcode-select --install` in terminal, and got another error below:

> Couldn't load plugin 'LDMP' due to an error when calling its classFactory() method 

KeyError: 'Can only index numba types with slices with no start or stop, got 4.' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/__init__.py", line 49, in classFactory
    from LDMP.plugin import LDMPPlugin
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/plugin.py", line 24, in 
    from LDMP.download_data import DlgDownload
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/download_data.py", line 30, in 
    from LDMP.calculate import DlgCalculateBase, get_script_slug
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 59, in 
    from LDMP.calculate_numba import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/zhangting/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate_numba.py", line 130, in 
    @cc.export('ldn_total_deg', 'f4[4](i2[:,:], b1[:,:], f4[:,:])')
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/pycc/cc.py", line 136, in export
    fn_args, fn_retty = sigutils.normalize_signature(sig)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/sigutils.py", line 24, in normalize_signature
    parsed = _parse_signature_string(sig)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/sigutils.py", line 14, in _parse_signature_string
    return eval(signature_str, {}, types.__dict__)
  File "", line 1, in 
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/types/abstract.py", line 185, in __getitem__
    ndim, layout = self._determine_array_spec(args)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg/numba/core/types/abstract.py", line 210, in _determine_array_spec
    raise KeyError(f"Can only index numba types with slices with no start or stop, got {args}.")
KeyError: 'Can only index numba types with slices with no start or stop, got 4.'


Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.18.1-Zürich Zürich, 202f1bf7e5
