### ISSUE TITLE
Can't set 2020 as ending year in Productivity calculation

### ISSUE THREAD

**Issue by Gengiska** [ConservationInternational/trends.earth#486]
In the trends.earth tool, i would like to calculate Productivity using MODIS in the period 2012-2020, but i can't set 2020 as ending year in any of the three sub (sub) indicators.

![Immagine](https://user-images.githubusercontent.com/24319811/123096472-6b14aa80-d42f-11eb-8508-5571dd1e98b9.png)

**Comment by azvoleff** [comment]
This is fixed in latest development version - stay tuned for a stable release this week
