### ISSUE TITLE
 Error removing file at...

### ISSUE THREAD

**Issue by thughes101** [ConservationInternational/trends.earth#500]
I get the following error when running Step 2 of Calculate SDG 15.3.1 Indicator:

![image](https://user-images.githubusercontent.com/61457335/130207751-1784cc80-8c88-4d59-b676-994ee216d040.png)

The file does not exist and I get the same whenever choosing a new basename on the output tab.

Any ideas??

**Comment by thughes101** [comment]
I'm running on QGIS 3.16.10

**Comment by kevmwenda** [comment]
I'm experiencing the same issue running the latest plugin on QGIS 3.16.10.

**Comment by kevmwenda** [comment]
I am encountering a similar issue using the latest plugin (1.0.6) on QGIS 3.16.10
