### ISSUE TITLE
Area calculation on json geometry and totals for land cover per year do not match

### ISSUE THREAD

**Issue by cjvandiemen** [ConservationInternational/trends.earth#506]
The total area that can be calculated using the geometry in the exported json file and the totals for land cover for each year do not match. 

``` 
# calculate area
import glob
import json

import geopandas as gpd
from shapely.geometry import shape
from rasterio.crs import CRS

country_code = 'GEO'

# load file
fn_json_summary = glob.glob(f'../data/{country_code}/sdg-15-3-1*summary.json')[0]
print('file used:', fn_json_summary,)

f = open(fn_json_summary)
dict_json_summary = json.load(f)

# read geometry
crs_source = CRS.from_wkt(dict_json_summary['metadata']['area_of_interest']['crs_wkt'])
geom = shape(dict_json_summary['metadata']['area_of_interest']['geojson']['features'][0]['geometry'])
gdf = gpd.GeoDataFrame(dict_json_summary['metadata']['area_of_interest']['geojson']).set_geometry([geom]).drop('features', axis =1).set_crs(crs_source)

# Reproject to: Lambert azimuthal equal area centered on polygon centroid
# epsg:102017, proj4: '+proj=laea +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs '

x_centroid = abs(gdf['geometry'][0].centroid.x)
y_centroid = abs(gdf['geometry'][0].centroid.y)
crs_target = CRS.from_proj4(f'+proj=laea +lat_0={y_centroid} +lon_0={x_centroid}')
total_area_geom = gdf.to_crs(crs_target)['geometry'][0].area / 1e6

# get land cover areas:
json_land_cover_years = dict_json_summary['land_condition']['baseline']['land_cover']['land_cover_areas_by_year']['values']
total_area_TE = sum([value for value in json_land_cover_years['2001'].values()]) 


print('Area difference: ',(total_area_geom - total_area_TE) * 1e6, 'sq m')
```

Output for ``country_code = 'ALB'``: 
```
file used: ../data/ALB/sdg-15-3-1-summary_albania-all-regions_202109211547_fa82dec3-150f-4d39-a0d1-1b5f11c80a33_summary.json
Area difference:  251930.4174093122 sq m
```

Output for ``country_code = 'GEO'``: 
```
file used: ../data/GEO/sdg-15-3-1-summary_shape-lon43.371lat42.321_202109211754_7b301758-d8cc-4209-a6bf-d415c2168e7a_summary.json
Area difference:  -955134.922376601 sq m
```

Output for ``country_code = 'FJI'``:
``` 
file used: ../data/FJI/sdg-15-3-1-summary_FJI - Prais_summary.json
Area difference:  901564.9302018574 sq m
```

This issue might be related to #302 and #339

**Comment by azvoleff** [comment]
That is only a difference of 0.95 sq km for Georgia, correct? So relative to the total area of Georgia a difference of around .0013%?

If so I'd say this isn't an issue, as this area was calculated in a different way than we do it in Trends.Earth. In Trends.earth we don't reproject to an equal area projection system as doing so would be too computationally costly for users given we are handling stacks of dozens of rasters. The [code we use is here](https://github.com/ConservationInternational/trends.earth/blob/develop/LDMP/localexecution/util_numba.py#L31). I'm actually surprised the difference is so small, I'd expect a slightly larger difference between the two methods.

**Comment by cjvandiemen** [comment]
Agreed, extremely small difference as part of the total.

**Comment by azvoleff** [comment]
Sounds good. And glad to hear they match closely! Haven't looked into this since discussions we had with Ish and others during the last round.

**Comment by leonidaslizarraga** [comment]
https://github.com/ConservationInternational/trends.earth/blob/develop/LDMP/localexecution/util_numba.py#L31 and  https://github.com/ConservationInternational/trends.earth/blob/develop/LDMP/localexecution/util_numba.py#L46

the links don´t work. I like to know how trends.earth calculate area. thanks.
