### ISSUE TITLE
Metadata editing workflow

### ISSUE THREAD

**Issue by timlinux** [ConservationInternational/trends.earth#518]
![image](https://user-images.githubusercontent.com/178003/148951183-98b4d77b-246f-4b69-9f40-38191350803d.png)

![image](https://user-images.githubusercontent.com/178003/148951277-39d233e1-29c2-4fe6-ba4e-f27b1eb52ed1.png)

![image](https://user-images.githubusercontent.com/178003/148951315-4e9a5d07-a960-4bb9-9a17-29bdef81c9cb.png)

Add metadata button on the form above

Once the layer is already loaded in the project  we can open the Dataset details window and then have a new button that will take us to the full QGIS layer properties dialog with the metadata tab opened

**Comment by timlinux** [comment]
If we can not match the state to the iso metadata model, dont try to store in the metadata

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/148955047-b23911f4-04de-414d-bd14-10268774c73c.png)


We already have an export as zip button, but Alex B needs to modify the function to export the metadata into an ISO doc and embed it in the zip.

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/148955244-3ad96f21-97bf-40b8-b299-101bf63ab810.png)


This existing document also needs to be refactored so that the data storage for the metadata is stored in the QGIS layer properties.

**Comment by timlinux** [comment]
So to summarise:

Phase 1:

 Alex B to hook in the layer properties so that layer metadata is stored in the QMD / QGIS layer metadata:
 Then add functionality so that we can transform the QGIS metadata into an ISO doc (look in metacat bridge plugin for inspiratio)
 Lastly when the layer properties export to Zip buttion is pressed, the ISO doc should be bundled in
 
 
 Phases 2: 
 
 Alex Z will be including extra metadata in e.g. json doc with the layer payload that comes from google EE
 Alex B to parse that and include as part of layer metadata and surface in the above T.E layer properties dialog

**Comment by alexbruy** [comment]
Splitting Phase1 into smaller task for better manageability:

- [ ] Update all dialogs for loading custom datasets (Soil Organic Carbon, Land Cover, Land Productivity) by adding a "Metadata" button to them. Clicking on this button will open a metadata editor identical to QGIS metadata editor where user can enter metadata of the dataset. Metadata is stored in the QGIS layer properties and in XML file.
- [ ] Add "Metadata" button to the "Dataset Details" dialog. Clicking of this button will open a layer properties dialog with Metadata tab activated. Populate some metadata automatically based on the available information.
- [ ] Implement conversion from QGIS metadata to ISO format
- [ ] Include metadata in ISO format into exported ZIP file when user clicks "Export as ZIP" button in the Dataset Details dialog

Feel free to edit or add other sub-tasks if I have missed something.

**Comment by alexbruy** [comment]
@azvoleff are you ok with the subtasks above? Do they cover all required functionality?

**Comment by alexbruy** [comment]
Adding screenshots of the metadata dialog which is used for imported custom datasets
![metadat-01](https://user-images.githubusercontent.com/776954/149980526-db21a7c5-abe4-40d0-a217-5ff88aab0d27.png)
![metadat-02](https://user-images.githubusercontent.com/776954/149980531-83bb803c-d668-4cfa-9d56-75d7b8f9e962.png)
![metadat-03](https://user-images.githubusercontent.com/776954/149980533-48740414-a82c-468b-8c60-72fdeaf10c54.png)
![metadat-04](https://user-images.githubusercontent.com/776954/149980535-80c8bb75-9cba-4b10-88c1-cf57e6fa469d.png)
![metadat-05](https://user-images.githubusercontent.com/776954/149980536-7b1b688d-a9e1-460e-854c-39c2a9822ddc.png)
![metadat-06](https://user-images.githubusercontent.com/776954/149980538-02c2103e-c600-4b2c-a4bf-2993ef45285c.png)
![metadat-07](https://user-images.githubusercontent.com/776954/149980539-3f74d416-aea1-4692-82bd-051da4255335.png)
![metadat-08](https://user-images.githubusercontent.com/776954/149980540-d485545e-4033-4646-b5e7-51e67a656503.png)

@azvoleff let me know if you want to keep this dialog or prefer custom simplified form. In the latter case having a mockup or at least list of required metadata will be very useful.

**Comment by azvoleff** [comment]
@boc84 do you have a list of the minimum set of fields you would like to require be entered for national-level datasets imported into Prais? I'd suggest we use a simplified version of the above dialogs to represent those fields (as a minimum). Users of course would then be free to use the standard QGIS metadata editing tools if they wanted to include further information (and for the default datasets, the values would of course be pre-filled).

**Comment by boc84** [comment]
@azvoleff Yes, these are basically the same fields as we have in our current upload form in PRAIS (presented to user on upload of any spatial dataset). Please use a simplified version of these, as you suggest. So my question would be if there is a some standard data structure behind these dialogs that is machine readable and can be easily imported to the database fields in PRAIS where metadata are stored? An item for discussion in our next catchup.

**Comment by boc84** [comment]
I attach a list of the minimum fields we have in PRAIS (our reporting system). These fields would suffice for the simplified version I think. 
[Metadata fields.docx](https://github.com/ConservationInternational/trends.earth/files/7905782/Metadata.fields.docx)

Please let me know if there are any other questions. Thanks for this work you are doing!

**Comment by alexbruy** [comment]
Initial work is here #527
