### ISSUE TITLE
Fix land cover import class definition screen

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#522]
- [x] reset button pulls up the full ESA class list (it should pull up correct codes for what is actually in the file)
- [x] save/reload of the definitions isn't working

@gdaldegan - can you expand if you notice any further issues with that screen?

**Comment by gdaldegan** [comment]
tool is returning 'nodata' dataset when importing a custom land cover layer into TE

**Comment by gdaldegan** [comment]
import LC vector (SHP) dataset returns the following error for the 'Edit definition' button, even though the dataset has only 5 lc classes
![edit_definition](https://user-images.githubusercontent.com/22821787/152243465-749d73ac-b6a1-4871-8596-9d081d7710fe.PNG)
n

**Comment by azvoleff** [comment]
@gdaldegan - do you still see this (whenever you get on the latest version)?

**Comment by gdaldegan** [comment]
just installed the latest exp. version on QGIS 3.22 and got the same message
![te_error](https://user-images.githubusercontent.com/22821787/163244106-14ba804f-c274-4c13-9d55-0dbeae59febe.PNG)
