### ISSUE TITLE
Wireframes needed for additional of summary statistics

### ISSUE THREAD

**Issue by timlinux** [ConservationInternational/trends.earth#532]
Could you please share a simple wireframe / mockup (e.g. made in powerpoint or your favorite drawing app) of what statistics and other content should be made available on the summary report.

**Comment by MLNoon** [comment]
Please find some examples here:
[wireframes for reports.docx](https://github.com/ConservationInternational/trends.earth/files/8027820/wireframes.for.reports.docx)
[sdg-15-3-1-summary_aruba-all-regions_baseline.xlsx](https://github.com/ConservationInternational/trends.earth/files/8027819/sdg-15-3-1-summary_aruba-all-regions_baseline.xlsx)
![map_figure_productivity_trajectory_degradation_2001_2015_Colombia_all_regions](https://user-images.githubusercontent.com/19840094/153083430-0f42b03c-18cb-423b-a92a-43c23426255a.png)
![map_complex_population_female_2015_Colombia_all_regions](https://user-images.githubusercontent.com/19840094/153083445-e2f75365-d4ac-43fe-9dbe-5cadcf851bce.png)

**Comment by gkahiu** [comment]
Thanks Monica. based on the sample stats in the document, will these only apply for land cover or also for other dataset categories?
