### ISSUE TITLE
UI for special areas

### ISSUE THREAD

**Issue by alexbruy** [ConservationInternational/trends.earth#538]
Add another tab to the plugin dock for listing known special areas. Implement UI (item delegate) to represent each layer in the list.
![Screenshot 2022-01-31 at 10-35-50 trends earth-metadata-reporting-enhancements-proposal-v1 5-nocosts pdf](https://user-images.githubusercontent.com/776954/151762301-53f08df9-f770-4f5c-8d90-9860ddd5f78d.png)

**Comment by alexbruy** [comment]
@azvoleff I was thinking about moving special areas to the Datasets tab. As I understand you want to have them in the same list mixed them with jobs items, right? In this case we will have items with different UI in the same list, is it ok? Or deeper reworking is needed to unify items as well?

**Comment by azvoleff** [comment]
(copied from email from @alexbruy):

> We extend the Results schema with new dataclasses VectorResults and 
> Vector which will describe a special area layer. Something like this
>
> class ResultType(enum.Enum):
>     CLOUD_RESULTS = "CloudResults"
>     RASTER_RESULTS = "RasterResults"
>     LOCAL_RESULTS = "LocalResults"
>     TIME_SERIES_TABLE = "TimeSeriesTable"
>     JSON_RESULTS = "JsonResults"
>     EMPTY_RESULTS = "EmptyResults"
>     VECTOR_RESULTS = "VectorResults"
>
> class VectorType(enum.Enum):
>     FALSE_POSITIVE = "False positive"
>
> @marshmallow_dataclass.dataclass
> class Vector:
>     uri: URI
>     type: VectorType = dataclasses.field(default=VectorType.FALSE_POSITIVE,
>                                          metadata={"by_value": True})

This works, but above should probably be `VectorFalsePositive` or similar to allow for multiple vector types (as we'll need a dataclass for each, with the VectorType enum used to differentiate on deserialization as you indicate)

> @marshmallow_dataclass.dataclass
> class VectorResults:
>     name: str
>     vector: Vector
>     type: ResultType = dataclasses.field(default=ResultType.VECTOR_RESULTS,
>                                          metadata={"by_value": True})
>
> Then when the user requests creation of the special area a new 
> dataset/job with VectorResults and status=GENERATED_LOCALLY is 
> created.
>
> However, adopting this approach brings some questions:
> 1. what to do with the UI inconsistence? Datasets and special areas 
> have different set of controls (buttons, progress bar, etc). We can 
> either show/hide not relevant controls or simply show all but 
> enable/disable some of them depending on the item type. In the first 
> case we will have different items in the same list and this can be 
> confusing for users. On the other hand keeping all controls visible 
> will result in cluttering the UI.

I'd argue for show/hide as relevant. We already do this for progress bar for example, given locally imported datasets never show one for example. If we could add a small icon though to each dataset indicating whether it is a raster or vector that could be a help in easily differentiating them. We'd also need a simple way to filter to just show one or the other (built on the current search box on top?).

> Also from the requirements document it seems that the amount of 
> information on the items is also different. For datasets we show name 
> plus area and date as a single string, while for special areas we need 
> name, creation date and area type.
>
> 2. do we need to provide some way to show only datasets/jobs or only 
> special areas? If yes, maybe you have a mockup of the UI?
>
> Looking forward to hearing your thoughts on this.

See above. Would it work to add a dataset type selector looking something like this (stealing the screenshots from the amazon searchbar...):

![chrome_gpE0i18aL9](https://user-images.githubusercontent.com/107753/152555587-e29e3051-bc74-4477-80e8-ed70d8c3189e.png)

![chrome_4PMtM7unI9](https://user-images.githubusercontent.com/107753/152555611-46c4af6b-f252-4c5f-8a06-ae5558509279.png)

Text might read "Dataset type: all" by default, with then options to instead filter to either "Dataset type: raster" or "Dataset type: vector".

**Comment by alexbruy** [comment]
Thanks for the feedback. Now I have to adopt the code which was written previously in assumption that we will handle special areas independently.

**Comment by alexbruy** [comment]
Related ticket to discuss attribute table structure and attribute form is here #543.

**Comment by alexbruy** [comment]
@azvoleff which workflow should be used for creating new features (polygons) in the special area layer? Will the same workflow as in native QGIS editing tools work? E.g. once layer added to project in editing mode then user selects desired digitizing tool, draws a polygon or create it from a point (buffer tool), then attribute form pop-ups where attributes of the newly added feature should be filled.

**Comment by alexbruy** [comment]
Addressed in #553.
