### ISSUE TITLE
UI for common report elements

### ISSUE THREAD

**Issue by timlinux** [ConservationInternational/trends.earth#542]
![imagem](https://user-images.githubusercontent.com/178003/152166006-6966edaa-489c-4766-83e2-e12464bf598f.png)

We should also have a way to let users provide their own templates in a user folder, masking out the ones shipped with the plugin.

**Comment by gkahiu** [comment]
@timlinux regarding the location of user templates, we can go with either of the two options below:
1. Directly editing the path of `portrait_path` and `landscape_path` in `LDMP/data/report/templates.json` with the absolute path of the user template(s):
```
{
      "template_info":{
         ...
         "portrait_path":"productivity_portrait.qpt",
         "landscape_path":"productivity_landscape.qpt",
         ...
}
```
Currently these paths are relative to the location of `templates.json` but I can make them to be both relative (for default templates) and absolute (for the user-defined templates); OR,

2. A user-defined folder containing a separate JSON file with a similar structure to the one in the plugin folder where the user can define their own templates.

Let me know what you think.

**Comment by gkahiu** [comment]
Alternatively, I will add an option in Settings to allow a user to specify a directory as a search path so that the path in `templates.json` can remain as relative.

**Comment by gkahiu** [comment]
PR #561 includes:
1. Settings for common report elements, which are also available as expression variables in the layout scope
2. By default, template configuration and corresponding templates are copied to `[BASE_DATA_DIR]/reports/templates`. The user can also defined an additional search path for templates - still under Settings > Reports

![image](https://user-images.githubusercontent.com/3840267/155487637-3b5c032a-a0af-4fbb-a240-ad0687b2ece0.png)
