### ISSUE TITLE
Charts on forms for special areas

### ISSUE THREAD

**Issue by timlinux** [ConservationInternational/trends.earth#556]
See #531 for reference

![image](https://user-images.githubusercontent.com/178003/151000677-5d5a15e9-3fd6-41c8-bb64-b63459308290.png)

![image](https://user-images.githubusercontent.com/178003/151000883-c3575df6-5e0a-42b9-84da-ee16ceeb4bd2.png)

Figure 2: Mockups for the digitizing form for the false positives/false negatives vector layer. (Charts would be added in
phase b)
We will use a standard QGIS table / form view and use actions for export / import if possible.
Alternatively we will implement a custom table view. We will save the layer in the Trends.Earth folder
and export and import are for putting a geojson copy in a user defined folder.
The calculation of the Indicator Values should be possible while the user is filling in the form (e.g. by
pressing a button) so as to permit the user to fill in other fields correctly.
This tool (the digitising workflow tool) will extract the pixels under each polygon area after each save
event (or similar e.g. by pressing a calculate button – client to confirm desired behaviour), populating
6 additional columns per polygon (on for each of the bars in the three bar charts), and calculate the
changes between the subsequent images. If needed, a consolidated list of these values document
containing the information in all 6 fields will be written to the Indicator Values field in the format
specified by the client.
Some generalisation in calculating these statistics will be acceptable. The resulting table (and
substructures used to generate the charts) will be exportable as JSON. We can store the raw data
directly in the polygon layer and use that for chart generation and any resulting export.
Partial pixels should be adequately counted in the calculation using interpolation techniques as
appropriate.

An example of how this calibration data is used on the server side:

https://gist.github.com/azvoleff/c2e6cf375c39b8aabe845098f0477f63

**Comment by timlinux** [comment]
The names of the layers used should be stored in the special areas metadata in the form of Task UUID and band number for each.

During the process of calculating areas, we should in addition use the area of the defined polygon to perform some calcs on the number of cells in the polygon in both degraded and improved state. These will be then populated (and updated when the polygon is latered) as per the field notes below.

The layer would have 8 additional fields, two for each of the indicators (productivity, landcover and soil carbon layer, sdg layer) , the first field being % improved and the second % degraded.

**Comment by alexbruy** [comment]
@azvoleff may I ask you to clarify digitizing workflow for charting version, as there are some things which are unclear for me.

Here is my understanding of the workflow:
1. user has SDG indicator layer added to canvas, this is one of the bands from sdg-15-3-1-sub-indicators process, right?)
2. user adds special area layer to canvas
3. user select either manual digitizing or buffer tool
4. a dialog pop-ups showing all raster layers loaded into QGIS where user can select up to 4 layers which should be used in charts calculation.
5. user digitize some area
6. when digitizing completed user presented with a form where in addition to existing fields there are 4 charts showing percentage of degraded and improved pixels relatively to the digitized area

Things which are unclear for me now:

1. How to select default layers based on the SDG layer?
    > We can set a sensible default for the SDG layer based on the process folder.
    > We can tell which the second three are based on the SDG layer selected so we can default.
2. Which metadata we are referring to for storing names of the raster layers: JSON job file or QGIS native metadata? In the latter case which field should be used for this information?
    > The names of the layers used should be stored in the special areas metadata in the form of Task UUID and band number for each.

Also looking at the different options to re-calculate charts when special area is altered, it seems this is not trivial and might require storing full paths to rasters and their band numbers in the special layers attributes. Is it ok to have more than 8 additional fields and store full paths to rasters in the attribute table? Can we assume that location of raster files won't change?

**Comment by alexbruy** [comment]
@azvoleff any comments on this?

**Comment by azvoleff** [comment]
> @azvoleff may I ask you to clarify digitizing workflow for charting version, as there are some things which are unclear for me.
> 
> Here is my understanding of the workflow:
> 
> 1. user has SDG indicator layer added to canvas, this is one of the bands from sdg-15-3-1-sub-indicators process, right?)
> 2. user adds special area layer to canvas

I would start with adding the false positive/false negative layer to the canvas. When a user decides to do so, then they should be asked which layer(s) it will apply to (so they should be shown a drop down to select which dataset, and (advanced option) layer(s).

The user should be given the option of selecting a dataset with an SDG layer inside it (with [this widget](https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/gui/WidgetDataIOSelectTEDatasetExisting.ui), and filtering for `dataset_type` equal to `sdg-15-3-1-summary`). The `sdg-15-3-1-summary` dataset selected should then prefil the initial values of four dropdown boxes (each dropdown should use [this widget](https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/gui/WidgetDataIOSelectTELayerExisting.ui)). The four dropdowns should be for the bands used for "SDG 15.3.1 indicator", "Productivity degradation", "Land cover degradation", and "Soil organic carbon degradation".

The above will allow the user to easily select a single dataset (the most common use case) and then construct a false positive/negative layer for that dataset. It will also allow advanced users to select alternative layers for land cover degradation, productivity degradation, etc., if desired (less common scenario, but still a needed functionality). This is very similar to what we do with the SDG summary tool ([this widget](https://github.com/ConservationInternational/trends.earth/blob/master/LDMP/gui/DlgCalculateLDNSummaryTableAdmin.ui), handled in [this code](https://github.com/ConservationInternational/trends.earth/blob/develop/LDMP/calculate_ldn.py#L378)). Those widgets also handle filtering datasets/layers to the selected region, so they are best to use here.

> 3. user select either manual digitizing or buffer tool
> 4. a dialog pop-ups showing all raster layers loaded into QGIS where user can select up to 4 layers which should be used in charts calculation.

See above - this step comes earlier in the process.

> 5. user digitize some area
> 6. when digitizing completed user presented with a form where in addition to existing fields there are 4 charts showing percentage of degraded and improved pixels relatively to the digitized area
> 
> Things which are unclear for me now:
> 
> 1. How to select default layers based on the SDG layer?
>    > We can set a sensible default for the SDG layer based on the process folder.
>    > We can tell which the second three are based on the SDG layer selected so we can default.

See above, this is basically matching my thinking.

> 2. Which metadata we are referring to for storing names of the raster layers: JSON job file or QGIS native metadata? In the latter case which field should be used for this information?

From the JSON. As you see [here](https://github.com/ConservationInternational/trends.earth/blob/develop/LDMP/data_io.py#L1427) the code looks for the `layer_type` property set in the widget, and then matches that against the [band name](https://github.com/ConservationInternational/trends.earth/blob/develop/LDMP/data_io.py#L1390). The `layer_type` values for the four "advanced" drop downs are:

- `SDG 15.3.1 Indicator` or ``SDG 15.3.1 Indicator` (status)`
- `Land Productivity Dynamics (from JRC)` or `Land Productivity Dynamics (from Trends.Earth)`
- `Land cover (degradation)`
- `Soil organic carbon (degradation)`

Note that for the first two bullets the combo boxes need to show layers with either of two possible `layer_type` values

>    > The names of the layers used should be stored in the special areas metadata in the form of Task UUID and band number for each.

Yes

> 
> Also looking at the different options to re-calculate charts when special area is altered, it seems this is not trivial and might require storing full paths to rasters and their band numbers in the special layers attributes. Is it ok to have more than 8 additional fields and store full paths to rasters in the attribute table? Can we assume that location of raster files won't change?

Yes, we can store additional fields. And fine to assume the location of the raster files won't change (so long as it fails with a useful error message if they DO change)

**Comment by timlinux** [comment]
Implemented and working originally, broken - see  #585
