### ISSUE TITLE
sdg15.3.1 summary table has issues on its Productivity & SOC tabs s

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#557]
Productivity & SOC tabs of the SDG15.3.1 Indicator Summary Table are not correctly reporting the summary figures
![sumaryTableIssue](https://user-images.githubusercontent.com/22821787/154382784-eb9a7626-07b5-4733-886a-0a0ee1d92820.PNG)
.

**Comment by gdaldegan** [comment]
@azvoleff this issue is still happening on the latest version, Productivity, SOC and Land Cover tabs are not correctly populated

**Comment by azvoleff** [comment]
Fixed by https://github.com/ConservationInternational/trends.earth-algorithms/commit/8d1175f2ba4e7a4522b02bc133c13a055fe244c3
