### ISSUE TITLE
 Download result problem

### ISSUE THREAD

**Issue by StudentFSL** [ConservationInternational/trends.earth#560]
I can successfully calculate the result but the download will show that unable to access internet. How to solve this problem?

![微信截图_20220223154524](https://user-images.githubusercontent.com/76092959/155301118-847bb2fc-4b89-4b40-95f0-cdd4ac51c1dd.png)
![微信截图_20220223154456](https://user-images.githubusercontent.com/76092959/155301134-ed59c5df-c232-4779-956c-f7674f83eb0c.png)

**Comment by azvoleff** [comment]
This looks like a temporary error with internet connectivity / an update on our API endpoint. If you still see this let us know and we'll reopen
