### ISSUE TITLE
We need to reinstate the NDVI point query tool

### ISSUE THREAD

**Issue by timlinux** [ConservationInternational/trends.earth#577]
This was removed in some refactoring last year. There is still the time series results alg in the code, but the UI interactions were removed. Can we please reinstate this functionality. @MLNoon if you could share some screenshots of the original tool, that would be great.

**Comment by MLNoon** [comment]
With Qv2, in Trends.Earth toolbar, we select the plot data icon.
![trends_earth_toolsbar_highlight_time_series_plot](https://user-images.githubusercontent.com/19840094/159776359-0129cbc6-88a6-446a-8550-687a99384cdf.png)
Then select AVHRR or MODIS, depending on time frame desired and resolution of dataset (example of AVHRR:)
![image](https://user-images.githubusercontent.com/19840094/159776456-1bc24906-3df6-4fcd-9af0-4abc10423422.png)
User selects an area of interest (I usually selected a point on the map when degradation results are preset and add that in the area). The submitted analysis returns a chart over the full time series of the dataset:
![image](https://user-images.githubusercontent.com/19840094/159776780-0a6116f7-b629-4e77-bc63-86ef183c6af9.png)
OR
![image](https://user-images.githubusercontent.com/19840094/159776809-d4fd3a5b-687e-4ab1-90f8-07ca8108fe88.png)
User can right-click on graph to export chart info:
![image](https://user-images.githubusercontent.com/19840094/159776929-30fe184e-3edd-450d-ad87-55e879ee6e32.png)

**Comment by alexbruy** [comment]
@MLNoon, @azvoleff how this tool should be exposed in the UI: in the same was as before by adding a button to the toolbar or in some other way?

**Comment by azvoleff** [comment]
I'd suggest a toolbar button in the main dock:

![image](https://user-images.githubusercontent.com/107753/160159379-4b9a8ba9-30cf-444f-a0c2-dc246a6b1bba.png)

Then the user could:

- click the button
- select a region/or a point
- click ok
- get back the plot once the results are ready from our API (with a QgsTask querying our API for results).

Alex

**Comment by timlinux** [comment]
@alexbruy could you take a look at this over the next week or two, or transfer this to @gkahiu if you are not able to spend time on this?

**Comment by gkahiu** [comment]
Hi @azvoleff, am trying to run generate some plots but am not getting any results with the job getting removed when refreshing remote state. See below the payload being sent to the server and corresponding job created from the response:

```
{
   "year_initial":2000,
   "year_final":2015,
   "crosses_180th":false,
   "geojsons":"[{\"coordinates\": [[[33.89046838400023, -4.677504164999959], [41.8850191650001, -4.677504164999959], [41.8850191650001, 5.030375822607752], [33.89046838400023, 5.030375822607752], [33.89046838400023, -4.677504164999959]]], \"type\": \"Polygon\"}]",
   "crs":"GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]",
   "ndvi_gee_dataset":"users/geflanddegradation/toolbox_datasets/ndvi_avhrr_1982_2015",
   "task_name":"Test Info",
   "task_notes":"",
   "climate_gee_dataset":"None",
   "trajectory_method":"ndvi_trend"
}
```

```
Job(id = UUID('39e798bf-68cc-412c-a7f5-40ee0ab8fc27'), params = {
    'climate_gee_dataset': None,
    'crosses_180th': False,
    'crs': 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]',
    'geojsons': '[{"coordinates": [[[33.89046838400023, -4.677504164999959], [41.8850191650001, -4.677504164999959], [41.8850191650001, 5.030375822607752], [33.89046838400023, 5.030375822607752], [33.89046838400023, -4.677504164999959]]], "type": "Polygon"}]',
    'ndvi_gee_dataset': 'users/geflanddegradation/toolbox_datasets/ndvi_avhrr_1982_2015',
    'trajectory_method': 'ndvi_trend',
    'year_final': 2015,
    'year_initial': 2000
}, progress = 0, 
start_date = datetime.datetime(2022, 6, 10, 17, 45, 15, 165078, 
tzinfo = datetime.timezone.utc), 
status = < JobStatus.PENDING: 'PENDING' > , 
local_context = JobLocalContext(base_dir = WindowsPath('D:/Frank/Kartoza/trends.earth/Data/trends_earth_data'), area_of_interest_name = 'kenya-all-regions'), 
results = EmptyResults(name = None, data_path = None, type = < ResultType.EMPTY_RESULTS: 'EmptyResults' > ), 
task_name = 'Test Info', 
task_notes = None, 
script = ExecutionScript(id = UUID('c0039c90-72c8-4955-b67c-1a4f92fb8e77'), 
run_mode = < AlgorithmRunMode.NOT_APPLICABLE: 0 > , 
name = '', 
slug = '', 
execution_callable = '', 
version = '', 
description = '', 
name_readable = '', 
additional_configuration = {}), 
end_date = datetime.datetime(2022, 6, 10, 17, 45, 15, 165083, tzinfo = datetime.timezone.utc), user_id = UUID('d09ca417-18e4-45db-a98e-490ac9712b4f'))
```

Is there something missing or a variable not set correctly especially for the payload?

**Comment by gkahiu** [comment]
Am getting a failed status on the job:

```
Thank you for using Trends.Earth. The below task has FAILED. More details on this task are below:

Task name: Plot Test Kenya
Job: time-series 1_99_11
Task ID: ffec0515-00ae-41cb-8841-489c6c2a87a5
Start time: 2022-06-14 14:26:52.631363
End time: 2022-06-14 14:26:55.544339
Status: FAILED
For more information, and to view the results, view the datasets window in the QGIS plugin.

Thank you, The Trends.Earth Team
```

**Comment by gkahiu** [comment]
Thanks, the update works now. I've opened a PR, let me know if it works as expected.
