### ISSUE TITLE
Error on Loading Plugin

### ISSUE THREAD

**Issue by gkahiu** [ConservationInternational/trends.earth#581]
The plugin is failing to load for commit 52042d00d404d2bda91255dc91a9df4400d60d33 in `develop` branch. Am encountering the following error:

![image](https://user-images.githubusercontent.com/3840267/159879707-f47ff023-7ee0-4a76-a749-6e03807d1885.png)

**Comment by azvoleff** [comment]
Looks like you’ll also need to upgrade `trends.earth-schemas` (@alexbruy added a new class there to handle the special areas tool).

**Comment by gkahiu** [comment]
Thanks, its working now!
