### ISSUE TITLE
Charting of false pos/negative datasets isn't working

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#585]
I tried a test for Botswana (admin 2 region "North East"). When I enter a polygon I assume I should get a chart. I just get a blank chart though:

![image](https://user-images.githubusercontent.com/107753/160156950-cb8b5ae2-c0f7-4004-9a2f-1a141eb3e538.png)

Possible I am doing something wrong? This is on [25ae4c8](https://github.com/ConservationInternational/trends.earth/commit/25ae4c8b48258c6bf814f31425a18b7dd2cfada7)

**Comment by azvoleff** [comment]
Also I get a Python error on trying to save the vector:

![image](https://user-images.githubusercontent.com/107753/160157834-04355efb-8786-40e7-9065-8fe915f6bc50.png)

**Comment by alexbruy** [comment]
Look like your rasters does not have valid pixel values: -1, 0 and 1 for degraded, stable and improved respectively.

**Comment by azvoleff** [comment]
That doesn't seem to be the issue. There actually were a few layers that used different coding (forgot one is a percentage, and the other 1-5). But I fixed that issue in the [vector_charting branch](https://github.com/ConservationInternational/trends.earth/tree/vector_charting), and I still don't get any charts - just blank charts without any error message. It seems the `calculate_charts` function never runs.

**Comment by alexbruy** [comment]
`calculate_charts` runs fine and produce correct results, but these values are not saved to the attribute table for some reason. Without the values in the fields it is not possible to display charts

**Comment by azvoleff** [comment]
I fixed the issue with special areas datasets related to serializing/deserializing vector JSONs (that came up in https://github.com/ConservationInternational/trends.earth/pull/590 in https://github.com/ConservationInternational/trends.earth-schemas/commit/d5b91c21933a569e335a4f869833ca9648ef3601 (so you'll need to update trends.earth-schemas). But this issue still remains - I get no charts from the tool.

**Comment by azvoleff** [comment]
The charting still isn't working on the latest version (even after merge of #600 and fix noted above for the issue noted in #590). Right now no charts come up during editing, and on clicking the edit button to stop editing a layer, I get:

![image](https://user-images.githubusercontent.com/107753/162205271-157d843c-63cf-4a8f-be63-3ab47443ea0b.png)
