### ISSUE TITLE
AttributeError: ReverseTransform 

### ISSUE THREAD

**Issue by paulterinho** [ConservationInternational/trends.earth#614]
Hi all, 

I'm not able to submit a request to "Urban Change and Land Consumption Inidcators" using the Calculator. Both options end in the same error (the "calculate urban change spatial layers", and "Calculate urban change summary table...") in Windows, Mac, or Linux. All result in a `AttributeError: ReverseTransform`

To reproduce: 
- QGIS 3.24 or 3.22 (Long term)
- Python 3.8
- Keep all the defaults the same except select Canada as the country, and Calgary as the city. 

Here's the resulting error. Was curious if anyone has a work around? (Perhaps I'm overlooking something?)

```
An error has occurred while executing Python code: 

AttributeError: ReverseTransform 
Traceback (most recent call last):
  File "/home/jeeves/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate_urban.py", line 152, in btn_calculate
    ret = super(DlgCalculateUrbanData, self).btn_calculate()
  File "/home/jeeves/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 1134, in btn_calculate
    ret = self.aoi.buffer(self.area_tab.buffer_size_km.value())
  File "/home/jeeves/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/calculate.py", line 391, in buffer
    geom_buffered.transform(to_aeqd, QgsCoordinateTransform.TransformDirection.ReverseTransform)
  File "/usr/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: ReverseTransform


Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0] 
QGIS version: 3.24.1-Tisler Tisler, 5709b82461 

Python Path:
/usr/share/qgis/python
/home/jeeves/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP/ext-libs
/home/jeeves/.local/share/QGIS/QGIS3/profiles/default/python
/home/jeeves/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/jeeves/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/jeeves/.local/share/QGIS/QGIS3/profiles/default/python
/home/jeeves/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LDMP
```

**Comment by azvoleff** [comment]
This is fixed in the latest develop version (was #583). Right now it is only available via installing from [the development zipfile or from source](https://github.com/ConservationInternational/trends.earth#installation-of-development-version-of-plugin), but we'll put up a new version (experimental pending final release of plugin v2.0) in the QGIS repo early next week.
