### ISSUE TITLE
Load dataset onto QGIS map area not working for custom data

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#619]
Apparently the 'Load dataset onto QGIS map area' function does not work when LP, LC or SOC sub-indicators are calculated using custom local data
![custom_data](https://user-images.githubusercontent.com/22821787/163055730-176d6c2a-6d72-4a4a-8271-8c2263ee86d7.png).

Not sure if this has been fixed already, given I'm not using the latest version of Trends.Earth.

**Comment by azvoleff** [comment]
Hmm... should be working but not sure. @gdaldegan if you add one of those as a zipfile here I'll try it on mine

**Comment by gdaldegan** [comment]
sharing as attachment
[uganda_custom_soc.zip](https://github.com/ConservationInternational/trends.earth/files/8482959/uganda_custom_soc.zip)

**Comment by azvoleff** [comment]
Looks like it works on the current version:

![image](https://user-images.githubusercontent.com/107753/163235363-7ec40ecf-c218-429b-8058-9ba5eead9825.png)

**Comment by azvoleff** [comment]
Fixed in d5e8dbf0a79d85ade806561cc86f88d2af113ae8
