### ISSUE TITLE
Include 'No Data' in Land Cover Edit Definition

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#621]
currently 'no data' is not available in the list of land cover classes
![lc_list](https://user-images.githubusercontent.com/22821787/164120093-91200652-c8df-4dfb-9202-3e607c4e5ebc.png)

**Comment by azvoleff** [comment]
Whoops. Should be

**Comment by azvoleff** [comment]
Fixed in 3acf2f9.
