### ISSUE TITLE
python error when importing custom LC data

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#622]
getting the following error when importing a custom land cover dataset
![custom_lc_error](https://user-images.githubusercontent.com/22821787/164121685-7b5cb2ee-e8c0-4da9-9e8e-eb9d7c7b93c2.png)

**Comment by azvoleff** [comment]
Can you post a screenshot of the Trends.Earth about page (from clicking on the red Trends logo in QGIS)?

**Comment by gdaldegan** [comment]
![te_version](https://user-images.githubusercontent.com/22821787/164290048-58025f57-9f2f-434a-90dd-064d9d774481.PNG)

**Comment by azvoleff** [comment]
😕 so I can't blame it on an old version...

**Comment by azvoleff** [comment]
@gdaldegan I can't reproduce this. Can you confirm you still see this on the latest zipfile? And if so, can you post the file giving an issue?

**Comment by gdaldegan** [comment]
getting these now:  
![custom_lc_error3](https://user-images.githubusercontent.com/22821787/165640697-faed53cd-fdf7-4023-8b1b-0ba36f7162ed.PNG)

![custom_lc_error4](https://user-images.githubusercontent.com/22821787/165640721-13bcab07-f125-47f6-a5b9-fba80da3f69d.PNG)

![te_version](https://user-images.githubusercontent.com/22821787/165640747-e506b4f5-22db-4f62-a412-7b0ee5b3ffb8.PNG)

**Comment by gdaldegan** [comment]
tested both running Land Cover remotely and importing custom lc, everything went smoothly.
