### ISSUE TITLE
Python error when running Drought vulnerability summary table

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#627]
![drought_error_2](https://user-images.githubusercontent.com/22821787/165160939-9431b8b3-01e2-4783-ba6d-a07c54a9e8d8.PNG)

**Comment by azvoleff** [comment]
Should be fixed by df2304d. @gdaldegan can you confirm this is working for you now?

**Comment by gdaldegan** [comment]
yep, Drought Summary running without triggering any error. However, the output summary spreadsheet doesn't look right, as all land and population are reported under the Non-Drought class, which does not seem correct overlaying the maps - ran it only for Colombia so far
[drought-vulnerability-summary_colombia-all-regions-buffer-10.000_summary.xlsx](https://github.com/ConservationInternational/trends.earth/files/8584479/drought-vulnerability-summary_colombia-all-regions-buffer-10.000_summary.xlsx)
.

**Comment by azvoleff** [comment]
Thanks, looking into this

**Comment by azvoleff** [comment]
@gdaldegan Can you try this again with the latest zipfile version? I can't seem to reproduce this.
