### ISSUE TITLE
Font size too small on Generate data package for UNCCD reporting function

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#628]
Description font size is too small for reading:
![sdg15_lpd_unccd_reporting_COL](https://user-images.githubusercontent.com/22821787/165172492-55b49bc7-c1b3-45a2-9a44-b347af00ea24.PNG)

**Comment by gkahiu** [comment]
Unable to reproduce in both 1080 and 4K resolutions. However, my description seems to be different...

![image](https://user-images.githubusercontent.com/3840267/166484989-0a2002b5-3557-42ea-9520-3a60c497c52e.png)

Which commit are you running?

**Comment by gdaldegan** [comment]
current version i'm running:
![te_version](https://user-images.githubusercontent.com/22821787/166515830-3a3443de-486b-4427-93d1-8bf22482d722.PNG)

Just checked the description:
![font_size](https://user-images.githubusercontent.com/22821787/166515945-3180b792-5ed3-43f9-8ece-0846a59b01f0.PNG)
