### ISSUE TITLE
Python error when importing existing trends.earth output file

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#631]
![import_error](https://user-images.githubusercontent.com/22821787/165621635-de3ecab1-cf06-4b94-938c-71cd38d0041b.PNG)

**Comment by azvoleff** [comment]
@gdaldegan - can you post the file that gave you this error?

**Comment by gdaldegan** [comment]
GitHub is not allowing me to post it here, sent via Teams

**Comment by azvoleff** [comment]
Thanks. I don't get a Python error, but on mine it doesn't correctly pick up the path for the data so you can't add it to the map. Looking into it
