### ISSUE TITLE
Nesting of land cover legend for imported local custom data

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#643]
I don't think Trends.Earth should have the rule below, given it is quite common to have distinct land cover classes between the initial and final layers.
![nesting](https://user-images.githubusercontent.com/22821787/167520022-129ac028-1fbb-4520-bf6f-466640faa5b7.png)

**Comment by azvoleff** [comment]
Can you tell me more what scenario we'd need this for @gdaldegan? My thought would be that if you have two different legends, then you shouldn't be calculating change among the two layers - I'm not sure how you'd know whether any "change" is due to actual change on the land, a change in class name between the two legends, or a change in class definition between the two legends.

**Comment by gdaldegan** [comment]
I'm trying to run Land Cover Change sub-indicator using imported custom LC layers for a small subset of the Colombian Amazon region.
Importing LC 2000, the original data doesn't have the class 13
![lc_2000](https://user-images.githubusercontent.com/22821787/168130570-7ebbab96-f966-4e91-9069-9181f750dfb8.png)

Class 13 is a non-forest natural vegetation, which in my interpretation likely represents forest pixels that were cleared at some point early to mid the 15y time-series and than abandoned, so began a natural regeneration succession - LC Legend:
![lc_classes](https://user-images.githubusercontent.com/22821787/168130503-8782d18b-015f-474a-9564-67c00199fc66.jpg)

This scenario is very likely to happen in recently occupied natural landscapes.

When importing LC 2015, which now does have class 13, I match it to Grassland for a lack of another standard class. 
![lc_2015](https://user-images.githubusercontent.com/22821787/168130717-16ca28b3-8729-401d-b07a-51f4cc4714bb.png)

Then trying to run LC Change, I get that message
![lc_nesting](https://user-images.githubusercontent.com/22821787/168132937-1267d15e-b407-47e4-b34b-f2c975685cb7.png)

Thus I don't fully understand the rule, given I'm matching the original classes to the 7 standard UNCCD classes:
![lc_imported](https://user-images.githubusercontent.com/22821787/168133832-0ffa0291-0bed-46e4-b612-b678ddd5c1f6.png)

**Comment by azvoleff** [comment]
No longer an issue with new LC tool
