### ISSUE TITLE
wrong bands for Baseline & Progress Period - Sub-indicators SDG 15.3.1 function

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#646]
Looks like resulting bands for Land Cover and SOC of Baseline & Progress are inverted and/or mixed up. After running all sub-indicators in one-step, I get the following list of bands for Baseline (2000-2015): 

![bsln](https://user-images.githubusercontent.com/22821787/167720711-343188cf-6b38-414d-8579-6e395ac61412.png)
 

and this list of band for Progress (2015-2019):

![pgrs](https://user-images.githubusercontent.com/22821787/167720944-89ce82b3-7c33-462a-abf6-cd920d0da7e9.png)

**Comment by gdaldegan** [comment]
Then it also gets mixed up when running Indicator for SDG 15.3.1:
![bsln_pgrs](https://user-images.githubusercontent.com/22821787/167721719-84bba351-0e3e-420e-8ce8-d01d1375d9d6.png)

**Comment by azvoleff** [comment]
Thanks. Which version is this on? I fixed this over the weekend (it's related to the presets), but may not have pushed it.

**Comment by gdaldegan** [comment]
I downloaded the latest version and it looks good! thanks!

![te_version](https://user-images.githubusercontent.com/22821787/167903856-f0f210af-03b2-4047-94c5-3594c407115f.png)
