### ISSUE TITLE
Move trends.earth settings into main QGIS settings window

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#667]
Currently settings for Trends.Earth are accessed from the plugin toolbar:

![image](https://user-images.githubusercontent.com/107753/177764642-f248e91a-42a0-494c-99d8-24d61b7de7d6.png)

This brings up what has become a very cramped window:

![image](https://user-images.githubusercontent.com/107753/177764716-7b1d2ecc-bb18-4190-a6d8-fa6b5980610a.png)

We should move these settings into the main QGIS options screen:

![image](https://user-images.githubusercontent.com/107753/177764818-b61261da-8c43-48bf-82c9-618afec0cf42.png)

We do need to keep the functionality to change regions and the land cover legend easily accessible though, so we'll need a way for a user to click on the "Change region" button in the various tools (and similarly for land cover legend) and directly bring up that page in the main QGIS options window.

**Comment by azvoleff** [comment]
Also see #397

**Comment by vermeulendivan** [comment]
This has been done: https://github.com/ConservationInternational/trends.earth/pull/705
