### ISSUE TITLE
Migrate cartoDB

### ISSUE THREAD

**Issue by vermeulendivan** [ConservationInternational/trends.earth#695]
Description: CaroDB is an online data visualisation platform for geospatial information. It is open source and self hosted by CI. The version in use at the moment is currently end of lifed. We will support CI to upgrade this to the latest version.

Assignees: TBD in conjunction with Monica

**Comment by timlinux** [comment]
Probably we should manage this outside of this github project @vermeulendivan  since it does not direcly relate to Trends plugin.

**Comment by vermeulendivan** [comment]
@timlinux @azvoleff This issue is now closed and moved here https://github.com/ConservationInternational/resilienceatlas/issues/64
