### ISSUE TITLE
Offline mode for the plugin

### ISSUE THREAD

**Issue by vermeulendivan** [ConservationInternational/trends.earth#697]
Add to the settings an offline mode for when a user needs to work offline (e.g. no internet connection close available). Add to the QGIS plugin settings panel:
![image](https://user-images.githubusercontent.com/79740955/195810014-e2adbd46-a745-4c6c-b4c7-b67847d0010e.png)

Should cover the following:
- Hide/disable function or algorithms which is not available during offline mode
- Tell the user if offline mode is active
- R&D: Check if its possible to add a bandwidth speed tester for slow internet connections

**Comment by vermeulendivan** [comment]
The plugin seems to do requests in the background, even a person is not using the plugin or if the plugin has finished an algorithm already. These requests needs to be investigated.

**Comment by vermeulendivan** [comment]
It might also be best to do this once the network migration has been done.

**Comment by vermeulendivan** [comment]
@azvoleff For now I've added the 'Offline mode' check box in the 'Advanced' section of the settings. If you prefer under location let me know.
![image](https://user-images.githubusercontent.com/79740955/206464551-3e70832e-d3f4-4822-8d72-66d12eb684aa.png)

**Comment by azvoleff** [comment]
That makes sense. Can you
- move it so it is third on the list (so just above "Download remotely-generated..."?
- when offline mode is enabled then the "Download remotely-generated...", "Poll remote processing..." and "Polling frequency..." settings should be disabled (greyed out). When it is turned off (so the plugin is online), those settings should be enabled

**Comment by vermeulendivan** [comment]
@azvoleff Thanks for the quick response! Will do so.

**Comment by vermeulendivan** [comment]
@azvoleff Here is the pull request for this https://github.com/ConservationInternational/trends.earth/pull/749
