### ISSUE TITLE
Add new dataset jobs to the top of the list

### ISSUE THREAD

**Issue by vermeulendivan** [ConservationInternational/trends.earth#703]
Currently new jobs are added to the bottom of the datasets list when a job is performed. This can get problematic when a user already has a large number of jobs/datasets in the list.

The suggested change is the rather add the new job or datasets to the top of the list. See below.

![image](https://user-images.githubusercontent.com/79740955/195815417-748acea8-4286-41a7-a00d-b5acdf58a760.png)

**Comment by azvoleff** [comment]
@vermeulendivan agreed. Jobs should be sorted chronologically. They usually are on my machine. Are they not working correctly on yours? In the above screenshot they appear to be sorted correctly.

**Comment by azvoleff** [comment]
Sounds good, thanks
