### ISSUE TITLE
Landcover error when saving class changes

### ISSUE THREAD

**Issue by vermeulendivan** [ConservationInternational/trends.earth#706]
When adding/deleting classes and saving it a crash occurs, BUT all of the storing of the settings/classes still occurs as it should.

![image](https://user-images.githubusercontent.com/79740955/198364294-837b1d45-05aa-4133-a915-62300659ab11.png)

**Comment by azvoleff** [comment]
@Samweli - I can't reproduce. Do you still see this?

**Comment by vermeulendivan** [comment]
@azvoleff This happened quite a lot to me, but not for a while now. A quick test showed it no longer happens. It likely got fixed by some other change to plugin.
