### ISSUE TITLE
Missing function get_file_metadata

### ISSUE THREAD

**Issue by Samweli** [ConservationInternational/trends.earth#710]
File `layer.py` in the plugin root source directory uses undefined function called `get_file_metadata`. The access statement is here https://github.com/ConservationInternational/trends.earth/blob/eed6bf191223e4bc3390ad550b797ba9b31bdae4/LDMP/layers.py#L753

This causes the recent PRs to fail in the CI tests, see https://github.com/ConservationInternational/trends.earth/actions/runs/3392701312/jobs/5639192723#step:5:682

**Comment by azvoleff** [comment]
This should be fixed by 80f3c8aedd074aecfcf7481d93fc74bdfdf0f153
