### ISSUE TITLE
Indicator for SDG 15.3.1 raise error when certain regions are used

### ISSUE THREAD

**Issue by Samweli** [ConservationInternational/trends.earth#723]
After choosing Finland with all regions as targeted algorithm region, loading up the dialog for Indicator SDG 15.3.1 inputs throws the following error

![image](https://user-images.githubusercontent.com/2663775/202731151-f9f2552e-925a-489c-ae4d-e136be79ebea.png)

**Comment by azvoleff** [comment]
I can't reproduce this - @Samweli can you please tell me the steps you used to install the plugin? It looks like either your data folder is missing or the step to download the admin boundaries failed, but without further detail I can't offer much more.

**Comment by azvoleff** [comment]
@Samweli - checking in again on this one. Do you still see this? I wasn't able to reproduce.

**Comment by Samweli** [comment]
@azvoleff no It hasn't happened again from my side, I guess it wasn't triggered by the regions. I try to reproduce it and get back to you, thanks.
