### ISSUE TITLE
Make size of land cover degradation matrix larger when a large number of classes is chosen

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#725]
When a large number of land cover classes are chosen, the window to setup the land cover degradation matrix should increase in size so that more rows of the matrix are shown (below is from the SDG 15.3.1 tool, but same goes for the land cover tool as well):

![image](https://user-images.githubusercontent.com/107753/202783215-6d1cac0b-7a29-49c9-80e5-2a2f025d6349.png)

**Comment by vermeulendivan** [comment]
@azvoleff Is this related to the Landcover table in the settings?

**Comment by azvoleff** [comment]
@vermeulendivan yes, if the number of classes is increased in the land cover table in settings then this matrix increases in size

**Comment by vermeulendivan** [comment]
Minor change to limit the size of the cells when there are only a few LC classes. Otherwise this is done.

**Comment by vermeulendivan** [comment]
@azvoleff Here you go: https://github.com/ConservationInternational/trends.earth/pull/746.
Some of the tests are failing, but all of it refers to LDN and urban, and has no reference to the code I worked on for this.
