### ISSUE TITLE
Ensure signal is sent to reload layer selection dropdowns on region change

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#727]
Sometimes if a user changes the region in the settings window from within a dialog box, the layer dropdowns won't reload (for example the "Land cover change" tool for the initial and target year fields below):

![image](https://user-images.githubusercontent.com/107753/202785378-fa24838a-30ff-4bd9-b46f-e17ade2c0660.png)

To reproduce, change the region in settings to one with data available - the dropdowns should then immediately populate with data available for that region, but doesn't consistently do this.

**Comment by vermeulendivan** [comment]
@azvoleff Want to have a go at this, but unsure what the initial year layer and the target year layer should be. Any guidance you can provide? Busy downloading landcover using the remote execution, but will only be able to have a look once its done.
Also, when clicking on the 'Help' at the button righ-hand corner, nothing happens. Is this normal?
![image](https://user-images.githubusercontent.com/79740955/206448951-51b1f260-9adf-4652-aaf6-d2721c928d60.png)

**Comment by azvoleff** [comment]
Actually I have this one figures out @vermeulendivan (came across it in another user issue). Should be fixed by f47c2dc8

**Comment by vermeulendivan** [comment]
@azvoleff Great to hear! Will then ignore this issue.
