### ISSUE TITLE
Plugin error when algorithms results don't return anything

### ISSUE THREAD

**Issue by Samweli** [ConservationInternational/trends.earth#738]
When running algorithms remotely its currently possible for the returned results to be `None` hence accessing any attributes from the results will cause the below error.
![image](https://user-images.githubusercontent.com/2663775/205013284-6b977f3e-535e-4387-a03b-f69e9b3b4a6c.png)

**Comment by azvoleff** [comment]
Fixed by [d29ccb6](https://github.com/ConservationInternational/trends.earth/commit/d29ccb693639234503cbbec374faf87ecb46f1d2).
