### ISSUE TITLE
Submitted Indicator for SDG15.3.1 job disappears from Datasets list

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#740]
I've been noticing that jobs ran using Indicator for SDG15.3.1 function disappears from the list submitted task displayed on the Datasets tab.

**Comment by azvoleff** [comment]
@gdaldegan - can you provide some more details on how to reproduce this one (does this always happen? or only intermittently) so @Samweli or others from the Kartoza team can look into it?

**Comment by azvoleff** [comment]
@vermeulendivan and @gdaldegan I think I tracked this down to an issue on our server. It should now be fixed. Let me know if you still see issues and I'll look back into it.

**Comment by vermeulendivan** [comment]
@azvoleff Did a test on my side, seems to work good now. Will inform you if it happens again.
