### ISSUE TITLE
Issue with the 'Create False Negative/Positive Layer' tool in TE v 2.1.6 [Spanish]

### ISSUE THREAD

**Issue by franklinp1975** [ConservationInternational/trends.earth#752]
Hi TE team, 

I executed the entire protocol [i.e., from 'Settings/ Custom Land Cover Classes' to 'Generate data package for UNCCD reporting'] using TE (v 2.1.6 in Spanish - revision fed0f996, 2012/12/08 22:03:09Z) and [Costa Rica's custom land covers](https://onedrive.live.com/?authkey=%21AFZsGqhc%5FHZYTWY&id=BCD971A407D5CDF3%217854&cid=BCD971A407D5CDF3) [i.e., 2001, 2015, and 2019]. No issues were found, except for the 'Create False Negative/Positive Layer' tool, which did not detect any previous rasters [I chose the Natural Earth boundary for Costa Rica; all previous algorithms worked fine].

![imagen](https://user-images.githubusercontent.com/54756387/207436560-0d6fb7e5-e249-4dd5-8011-747b3791040a.png)

In addition, this message is displayed: 
"2022-12-13T16:10:22     WARNING    Traceback (most recent call last):
              File"C:\Users/SENTINEL/AppData/Roaming/QGIS/QGIS3\profiles\SpanishWebinars/python/plugins\LDMP\select_dataset.py", line 69, in run_settings
              self.iface.showOptionsDialog(currentPage=OPTIONS_TITLE)
             AttributeError: 'DlgSelectDataset' object has no attribute 'iface'"

Thanks in advance.

-Franklin

**Comment by azvoleff** [comment]
@gabrieldaldegan - can you see if you can reproduce this in the latest zipfile version of the plugin? The `AttributeError: 'DlgSelectDataset' object has no attribute 'iface'"` Franklin mentions I know is fixed, and I think the issue of not having false pos/negative layers show up is fixed as well, but need to check that.

**Comment by gdaldegan** [comment]
getting a **TypeError 'int' object is not iterable** when I change the language of QGIS from/to English/Spanish

**Comment by gdaldegan** [comment]
currently running TE version 794ea402, 2023/01/09 19:56:52Z and facing the issue above described by Franklin. False positive/negative dialog is only recognizing the Productivity Degradation raster, all other fields are left blank: 

![Screenshot_20230111_094255](https://user-images.githubusercontent.com/22821787/211879964-6445cfe9-63c6-4653-91a9-984212c2ff05.png)

**Comment by gdaldegan** [comment]
When False Positive/Negative tools is functional (QGIS is set to English), the following Py Error is popping up while creating a vector delineating the area to recode: **AttributeError type object 'Qgis' has no attribute 'AvoidIntersectionsMode'**
