### ISSUE TITLE
Basemap dialog too small

### ISSUE THREAD

**Issue by vermeulendivan** [ConservationInternational/trends.earth#754]
When adding a basemap (Load base map) when on the Datasets tabs of the main dock widget the UI is too small for what is shown on the widget.

Add basemap dialog:
![image](https://user-images.githubusercontent.com/79740955/208437148-aecb334b-0dc6-4d63-8487-2aa83f660e0f.png)

The dialog can be opened here:
![image](https://user-images.githubusercontent.com/79740955/208437082-d64f19ab-63a0-4d37-8d61-a8c6f03a22cf.png)

**Comment by azvoleff** [comment]
Closing as appears to be fixed
