### ISSUE TITLE
trends.earth data download

### ISSUE THREAD

**Issue by simeonhengari** [ConservationInternational/trends.earth#76]
I am trying a data download from the trends.earth tool installed as a Plugin in QGIS.

This is the error I get:
1. An error has occurred while executing Python code: See message log (Python Error) for more details.

The Python message:
2. Traceback (most recent call last):
File "C:/Users/ngait/.qgis2/python/plugins\LDMP\download_data.py", line 128, in btn_calculate 'task_name': self.task_name.text(),
			AttributeError: 'DlgDownload' object has no attribute 'task_name'

**Comment by azvoleff** [comment]
This is fixed in the latest version of the tool (available in the zipfile now, or on the QGIS repository later this week).
