### ISSUE TITLE
error when running Drought vulnerability summary table

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#763]
consistently getting a Py Error popping up when running the Drought vulnerability summary table function using version2.1.7 revision 794ea402, 2023/01/09: **backoff_hdlr() missing 1 required positional argument: 'details'**

**Comment by azvoleff** [comment]
Thanks! Fixed in https://github.com/ConservationInternational/trends.earth/commit/4e0d7dfda86248ba83d807f8c311a6bc4881d565
