### ISSUE TITLE
pending in local execution for SDG 15.3.1 calculation

### ISSUE THREAD

**Issue by nabilabdessattar** [ConservationInternational/trends.earth#764]
Once the remote calculation for the different sub indicators LC, LPD and SOC were done and downloaded successfully, I tried to calculate the SDG 15.3.1 locally but the execution keeps pending and even when refresh datasets, the execution in datasets disappeared. Please, I need you help what issues there. Note I already used the latest plugin of 26 January 2023.
Thank you in advance!

**Comment by azvoleff** [comment]
Thanks @nabilabdessattar - can you let us know what area you are processing (and send a shapefile if need be), if you are using any custom datasets, and if any error messages are coming up? Also if you could please send us any log messages you see (see the fifth bullet [on this page](https://github.com/ConservationInternational/trends.earth#reporting-an-issue-error-possible-bug-etc)) that would be very useful.

**Comment by nabilabdessattar** [comment]
Hi Alex, thank you very much for your support!
I'm processing Madagascar, but I guess the problem is not due to the area, because I tried to process Libya as well but similar behavior. I attached a print-screen, where python warning messages are there. I guess the problem is internal in my machine
![python_warning](https://user-images.githubusercontent.com/123644825/214953079-baae37d4-f742-41fc-a5a2-eb3b07bcbc0a.jpg)
Note that when I make refresh SDG 15.3.1 disappeared. thank you again Alex

**Comment by azvoleff** [comment]
Thanks @nabilabdessattar. I don't see any errors, so I'm not sure what is going on (the post above is the warnings screen, which isn't anything to worry about). Can you copy/paste the content of the "trends.earth" log messages panel and post that here? That should help in diagnosing what is going on.

**Comment by nabilabdessattar** [comment]
Dear Alex, thank you for your message, yes the task finished, but it takes a lot of time unusual for me.
But, I would like to share with you an issue with the results is that maps showed different extent. I attached print-screen. Thank you in advance
![image](https://user-images.githubusercontent.com/123644825/215321967-063f4578-c7ee-47fe-a214-deaba6dabdd8.png)
![image](https://user-images.githubusercontent.com/123644825/215321993-0f801933-1d19-4ee1-91f6-e0a28c36f662.png)

**Comment by nabilabdessattar** [comment]
Hi everyone,
I got this message when I tried to change from country to country while using Trends.Earth
![image](https://user-images.githubusercontent.com/123644825/215968601-bfde01e4-1d37-48ad-802c-7f5f1222b3cf.png)

**Comment by azvoleff** [comment]
Thanks @nabilabdessattar. This looks like two different issues:
- The above error message (re `pushButton_download`), should now be fixed by 75300e1593b1e4d5036c84129fa2a7ced6edb30d. Let me know if you still see any issues.
- The area you are seeing south of Madagascar: that is a known bug, but can be ignored. The area you see south of Madagascar is showing up due to a big in the tiling code we use internally to split up the processing of the data. The extra tile that you see does not affect the statistics that are reported to UNCCD - that area is ignored. We'll release a fix for this after the reporting cycle as for now it is a lower priority for us

**Comment by nabilabdessattar** [comment]
Many thanks Alex,
All the best
