### ISSUE TITLE
Details of the WOCAT dataset

### ISSUE THREAD

**Issue by Sreetama21** [ConservationInternational/trends.earth#782]
Hello,
I just wanted to know if anyone could help me with the details of the WOCAT dataset. What is the resolution of the data used and it's limitations in comparison to the Trends Earth dataset ?

**Comment by azvoleff** [comment]
@Sreetama21 you can see more here: https://maps.tools4ldn.org/ and more specifically here: https://drive.google.com/file/d/1zq9QpIfHcXdvrnuLAMDtc9aeOkwfLZou/view?usp=sharing
