### ISSUE TITLE
Unable to login to Trends.Earth server 

### ISSUE THREAD

**Issue by Chandrakesh1997** [ConservationInternational/trends.earth#784]
I'm unable to login to Trends.Earth server. i tried most of the time. and download portion are also not highlighted.
![WhatsApp Image 2023-08-12 at 11 15 53 AM](https://github.com/ConservationInternational/trends.earth/assets/142076227/f6b24950-f071-4a6e-869a-3ea41d297dbb)
![IMG_20230701_101146 (1)](https://github.com/ConservationInternational/trends.earth/assets/142076227/21dcd7e3-4990-49e4-a8ef-77744674bd1d)

**Comment by Chandrakesh1997** [comment]
Please respond ASAP.

**Comment by MLNoon** [comment]
Hello, this looks like an issue with your internet connection. Can you kindly check your connection and try to log in again. Trends.Earth connects to our server when logging in, submitting tasks to the cloud and downloading results.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Chandrakesh1997 ***@***.***>
Sent: Saturday, August 12, 2023 1:48:01 AM
To: ConservationInternational/trends.earth ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ConservationInternational/trends.earth] Unable to login to Trends.Earth server (Issue #784)


EXTERNAL EMAIL:  CAUTION before you click/open

I'm unable to login to Trends.Earth server. i tried most of the time. and download portion are also not highlighted.
[WhatsApp Image 2023-08-12 at 11 15 53 AM]<https://user-images.githubusercontent.com/142076227/260203689-f6b24950-f071-4a6e-869a-3ea41d297dbb.jpeg>
[IMG_20230701_101146 (1)]<https://user-images.githubusercontent.com/142076227/260203692-21dcd7e3-4990-49e4-a8ef-77744674bd1d.jpg>
