### ISSUE TITLE
Submitted Indicator for Drought and SDG15.3.1 job disappears from Datasets list 

### ISSUE THREAD

**Issue by Francescaforest** [ConservationInternational/trends.earth#808]
Hello,
I've been noticing that jobs run using the Indicator for SDG15.3.1 and the Drought function disappear from the list of submitted tasks displayed on the Datasets tab. I've tried with different computers and versions of QGIS (3.26, 3.28, and 3.34) but it still doesn't work.

Am I doing anything wrong, or is this a bug in the system?

**Comment by azvoleff** [comment]
This should now be fixed - let us know if you are still seeing this issue.
