### ISSUE TITLE
land cover classes in Russian by default

### ISSUE THREAD

**Issue by gdaldegan** [ConservationInternational/trends.earth#826]
Land cover classes descriptions are shown in Russian by default when trying to Edit Definition under Land Cover Setup>Aggregation Method: 
![image](https://github.com/ConservationInternational/trends.earth/assets/22821787/75e0df53-fad1-41b0-a9c3-4b49a624fd7c)

**Comment by azvoleff** [comment]
Odd, I can't reproduce this. Are you still seeing this @gdaldegan?
