### ISSUE TITLE
Move soc to original asset name

### ISSUE THREAD

**Issue by azvoleff** [ConservationInternational/trends.earth#83]
@mgroglich - can you move the SOC data from Ish to: soc_sgrid_30cm? Right now I am using it from: users/geflanddegradation/toolbox_datasets/soc_sgrid_30cm_unccd_20180111.

Just so it is consistent with the data download tool, etc.

**Comment by mgroglich** [comment]
Done!

**Comment by azvoleff** [comment]
Sorry, should have said - for now we need both. The current version of the toolbox that users have looks for SOC at soc_sgrid_30cm_unccd_20180111, but the new one will look at soc_sgrid_30cm. Can you copy the soc_sgrid_30cm to soc_sgrid_30cm_unccd_20180111 so both have the new UNCCD data there? If soc_sgrid_30cm_unccd_20180111 is missing the SOC calculation won't work until users update their toolbox.
